"use client";
import { useState, useEffect, useCallback } from "react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import {
  Check,
  CheckCircle,
  ChevronsUpDown,
  FileText,
  Loader2,
  XCircle,
} from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { supabase } from "../supabase";
import { fetchMasterData } from "../utils/masterDataUtils";

export default function IndentForm() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    generatedBy: "",
    vendorName: "",
    firmName: "",
    rawMaterialName: "",
    quantity: "",
    currentStock: "",
    notes: "",
    deliveryOrderNo: "",
    priority: "",
    typeOfIndent: "",
    uom: "",
  });
  const [errors, setErrors] = useState({});
  const [dropdownOptions, setDropdownOptions] = useState({
    generatedBy: [],
    vendorName: [],
    firmName: [],
    rawMaterialName: [],
    indentType: [],
    firmNameMapping: {},
    uom: [],
  });
  const [isLoading, setIsLoading] = useState(true);
  const [lastRINumberNumeric, setLastRINumberNumeric] = useState(0);
  const [rawMaterialOpen, setRawMaterialOpen] = useState(false);
  const [rawMaterialSearch, setRawMaterialSearch] = useState("");
  const { user, allowedSteps } = useAuth();

  const normalizedIndentType = formData.typeOfIndent.trim().toLowerCase();
  const shouldShowDeliveryOrder =
    normalizedIndentType === "finished goods" ||
    normalizedIndentType.includes("traiding") ||
    normalizedIndentType.includes("trading");
  const filteredRawMaterials = dropdownOptions.rawMaterialName.filter((option) =>
    option.toLowerCase().includes(rawMaterialSearch.trim().toLowerCase()),
  );

  const fetchLatestRINumber = useCallback(async () => {
    try {
      const { data, error } = await supabase
        .from("INDENT-PO")
        .select('"Indent Id.", id')
        .order("id", { ascending: false })
        .limit(1);

      if (error) throw error;

      if (data && data.length > 0) {
        const lastId = data[0]["Indent Id."];
        if (lastId && typeof lastId === "string") {
          // Match both RI- and RL- prefixes
          const match = lastId.match(/^(RI|RL)-(\d+)$/);
          if (match) {
            const num = parseInt(match[2], 10);
            if (!isNaN(num)) {
              setLastRINumberNumeric(num);
            }
          }
        }
      }
    } catch (error) {
      console.error("Error fetching latest RI number from Supabase:", error);
    }
  }, []);

  const APPS_SCRIPT_URL =
    "https://script.google.com/macros/s/AKfycbylQZLstOi0LyDisD6Z6KKC97pU5YJY2dDYVw2gtnW1fxZq9kz7wHBei4aZ8Ed-XKhKEA/exec";
  const SHEET_ID = "13_sHCFkVxAzPbel-k9BuUBFY-E11vdKJAOgvzhBMLMY";
  const SHEET_NAME = "INDENT-PO";

  const fetchData = useCallback(async () => {
    setIsLoading(true);
    try {
      // Fetch data from Supabase Master table
      const masterData = await fetchMasterData();

      let options = {
        generatedBy: masterData.generatedByOptions,
        vendorName: masterData.vendorOptions,
        firmName: masterData.firmNameOptions,
        rawMaterialName: masterData.materialOptions,
        indentType: masterData.indentTypeOptions,
        firmNameMapping: masterData.firmNameMapping || {},
        uom: masterData.uomOptions || [],
      };

      setDropdownOptions(options);
    } catch (error) {
      console.error("Error fetching master data:", error);
      toast.error("Failed to load initial form data.", {
        description: "Please try refreshing. Error: " + error.message,
        icon: <XCircle className="w-4 h-4" />,
      });
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
    fetchLatestRINumber();
  }, [fetchData, fetchLatestRINumber]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    if (errors[name]) {
      setErrors((prevErrors) => ({
        ...prevErrors,
        [name]: null,
      }));
    }
  };

  const handleSelectChange = (name, value) => {
    setFormData((prev) => {
      const newData = {
        ...prev,
        [name]: value,
      };

      // Auto-populate Generated By if Firm Name is changed
      if (name === "firmName" && dropdownOptions.firmNameMapping[value]) {
        newData.generatedBy = dropdownOptions.firmNameMapping[value];
      }

      return newData;
    });
    if (errors[name]) {
      setErrors((prevErrors) => ({
        ...prevErrors,
        [name]: null,
      }));
    }
    // Also clear errors for generatedBy if it was auto-populated
    if (name === "firmName" && dropdownOptions.firmNameMapping[value]) {
      setErrors((prevErrors) => ({
        ...prevErrors,
        generatedBy: null,
      }));
    }
  };

  const validateForm = () => {
    const newErrors = {};
    if (!formData.generatedBy)
      newErrors.generatedBy = "Generated By is required.";
    if (!formData.firmName) newErrors.firmName = "Firm Name is required.";
    if (!formData.rawMaterialName)
      newErrors.rawMaterialName = "Raw Material Name is required.";

    // Stricter check for Quantity
    if (!formData.quantity) {
      newErrors.quantity = "Quantity is required.";
    } else if (!/^-?\d*\.?\d+$/.test(formData.quantity)) {
      newErrors.quantity =
        "Please enter only valid numeric value for Quantity.";
    } else if (Number(formData.quantity) <= 0) {
      newErrors.quantity = "Quantity must be a positive number.";
    }

    // Stricter check for Current Stock
    if (!formData.currentStock) {
      newErrors.currentStock = "Current stock is required.";
    } else if (!/^-?\d*\.?\d+$/.test(formData.currentStock)) {
      newErrors.currentStock =
        "Please enter only valid numeric value for Current Stock.";
    }

    if (!formData.priority) newErrors.priority = "Priority is required.";
    if (!formData.typeOfIndent)
      newErrors.typeOfIndent = "Type Of Indent is required.";
    if (!formData.uom) newErrors.uom = "UOM is required.";

    if (shouldShowDeliveryOrder && !formData.deliveryOrderNo) {
      newErrors.deliveryOrderNo =
        "Delivery Order No. is required for the selected indent type.";
    }

    setErrors(newErrors); // Update state for UI error messages
    return newErrors; // Return errors immediately for synchronous check
  };

  async function handleSubmit(e) {
    e.preventDefault();
    const validationErrors = validateForm();

    if (Object.keys(validationErrors).length > 0) {
      const firstErrorKey = Object.keys(validationErrors)[0];
      toast.error("Validation Error", {
        description: validationErrors[firstErrorKey],
        icon: <XCircle className="w-4 h-4" />,
      });
      return;
    }

    setIsSubmitting(true);
    try {
      // Re-fetch latest RI number from Supabase by ID order to ensure uniqueness
      const { data: latestData } = await supabase
        .from("INDENT-PO")
        .select('"Indent Id.", id')
        .order("id", { ascending: false })
        .limit(1);

      let currentMax = lastRINumberNumeric;
      if (latestData && latestData.length > 0) {
        const lastId = latestData[0]["Indent Id."];
        if (lastId && typeof lastId === "string") {
          const match = lastId.match(/^(RI|RL)-(\d+)$/);
          if (match) {
            const num = parseInt(match[2], 10);
            if (!isNaN(num) && num > currentMax) {
              currentMax = num;
            }
          }
        }
      }

      const nextNumericPart = currentMax + 1;
      const paddedNumber = String(nextNumericPart).padStart(3, "0");
      const riNumber = `RI-${paddedNumber}`;

      const now = new Date();
      // Format as YYYY-MM-DD HH:mm:ss (IST)
      const day = String(now.getDate()).padStart(2, "0");
      const month = String(now.getMonth() + 1).padStart(2, "0"); // Months are 0-indexed
      const year = now.getFullYear();
      const hours = String(now.getHours()).padStart(2, "0");
      const minutes = String(now.getMinutes()).padStart(2, "0");
      const seconds = String(now.getSeconds()).padStart(2, "0");

      const timestamp = `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;

      const { error: insertError } = await supabase.from("INDENT-PO").insert([
        {
          Timestamp: timestamp,
          "Indent Id.": riNumber,
          "Firm Name": formData.firmName,
          "Generated By": formData.generatedBy,
          Material: formData.rawMaterialName,
          Quantity: parseFloat(formData.quantity),
          "Current Stock As Per factory": parseFloat(formData.currentStock),
          Priority: formData.priority,
          "Type Of Indent": formData.typeOfIndent,
          "Delivery Order No.": formData.deliveryOrderNo || null, // Send null if empty
          Notes: formData.notes,
          UOM: formData.uom,
        },
      ]);

      if (insertError) throw insertError;

      setLastRINumberNumeric(nextNumericPart);
      toast.success("Success!", {
        description: `RI Number ${riNumber} generated successfully in Supabase!`,
        icon: <CheckCircle className="w-4 h-4" />,
      });

      // Reset the form
      setFormData({
        generatedBy: "",
        vendorName: "",
        firmName:
          user?.firmName && user.firmName.toLowerCase() !== "all"
            ? user.firmName
            : "",
        rawMaterialName: "",
        quantity: "",
        currentStock: "",
        notes: "",
        deliveryOrderNo: "",
        priority: "",
        typeOfIndent: "",
        uom: "",
      });
      setErrors({});
    } catch (error) {
      console.error("Error submitting form:", error);
      toast.error("Submission Failed", {
        description:
          error.message || "Failed to submit RI Number. Please try again.",
        icon: <XCircle className="w-4 h-4" />,
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-screen bg-slate-50">
        <Card className="w-full max-w-lg shadow-lg">
          <CardContent className="flex flex-col items-center justify-center p-12">
            <Loader2 className="w-12 h-12 text-primary animate-spin" />
            <p className="mt-4 ml-3 text-gray-700">Loading form data...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="w-full min-h-screen p-4 bg-slate-50 sm:p-6 lg:p-6">
      <Card className="w-full bg-white border border-gray-200 rounded-lg shadow-md">
        <CardHeader className="p-6 border-b border-gray-200">
          <CardTitle className="flex items-center gap-2 text-gray-700">
            <FileText className="w-6 h-6 text-primary" />
            Step 1: Generate Entry
          </CardTitle>
          <CardDescription className="text-gray-600">
            Fill out the form to generate a new entry with an RI Number
          </CardDescription>
          {user?.firmName && user.firmName.toLowerCase() !== "all" && (
            <p className="mt-1 text-sm text-primary">
              Creating entry for:{" "}
              <span className="font-semibold">{user.firmName}</span>
            </p>
          )}
        </CardHeader>
        <CardContent className="p-6 sm:p-8">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div>
                <Label htmlFor="firmName">
                  Firm Name <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="firmName"
                  value={formData.firmName}
                  onValueChange={(value) =>
                    handleSelectChange("firmName", value)
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.firmName ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select firm name" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.firmName.map((option, index) => (
                      <SelectItem key={`firm-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.firmName && (
                  <p className="mt-1 text-xs text-red-500">{errors.firmName}</p>
                )}
              </div>
              <div>
                <Label htmlFor="generatedBy">
                  Generated By <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="generatedBy"
                  value={formData.generatedBy}
                  onValueChange={(value) =>
                    handleSelectChange("generatedBy", value)
                  }
                  disabled={
                    formData.firmName &&
                    dropdownOptions.firmNameMapping[formData.firmName]
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.generatedBy ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select generator" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.generatedBy.map((option, index) => (
                      <SelectItem key={`gen-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.generatedBy && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.generatedBy}
                  </p>
                )}
              </div>
              {/* <div>
                <Label htmlFor="vendorName">Vendor Name <span className="text-red-500">*</span></Label>
                <Select
                  name="vendorName"
                  value={formData.vendorName}
                  onValueChange={(value) => handleSelectChange("vendorName", value)}
                >
                  <SelectTrigger className={`mt-1 ${errors.vendorName ? "border-red-500" : ""}`}>
                    <SelectValue placeholder="Select vendor" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.vendorName.map((option, index) => (
                      <SelectItem key={`ven-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.vendorName && <p className="mt-1 text-xs text-red-500">{errors.vendorName}</p>}
              </div> */}

              <div>
                <Label htmlFor="rawMaterialName">
                  Raw Material Name <span className="text-red-500">*</span>
                </Label>
                <Popover open={rawMaterialOpen} onOpenChange={setRawMaterialOpen}>
                  <PopoverTrigger asChild>
                    <Button
                      type="button"
                      variant="outline"
                      role="combobox"
                      aria-expanded={rawMaterialOpen}
                      className={`mt-1 w-full justify-between font-normal ${
                        errors.rawMaterialName ? "border-red-500" : ""
                      }`}
                    >
                      <span className="truncate">
                        {formData.rawMaterialName || "Select material"}
                      </span>
                      <ChevronsUpDown className="w-4 h-4 ml-2 opacity-50 shrink-0" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-2">
                    <Input
                      value={rawMaterialSearch}
                      onChange={(e) => setRawMaterialSearch(e.target.value)}
                      placeholder="Search raw material..."
                      className="mb-2"
                    />
                    <div className="max-h-60 overflow-y-auto">
                      {filteredRawMaterials.length > 0 ? (
                        filteredRawMaterials.map((option, index) => (
                          <button
                            key={`mat-${index}`}
                            type="button"
                            onClick={() => {
                              handleSelectChange("rawMaterialName", option);
                              setRawMaterialOpen(false);
                              setRawMaterialSearch("");
                            }}
                            className="flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm hover:bg-slate-100"
                          >
                            <span>{option}</span>
                            {formData.rawMaterialName === option && (
                              <Check className="w-4 h-4 text-primary" />
                            )}
                          </button>
                        ))
                      ) : (
                        <p className="px-3 py-2 text-sm text-gray-500">
                          No raw material found.
                        </p>
                      )}
                    </div>
                  </PopoverContent>
                </Popover>
                {errors.rawMaterialName && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.rawMaterialName}
                  </p>
                )}
              </div>

              <div>
                <Label htmlFor="quantity">
                  Quantity <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="quantity"
                  type="text"
                  inputMode="decimal"
                  name="quantity"
                  placeholder="Enter quantity"
                  value={formData.quantity}
                  onChange={handleChange}
                  className={`mt-1 ${errors.quantity ? "border-red-500" : ""}`}
                />
                {errors.quantity && (
                  <p className="mt-1 text-xs text-red-500">{errors.quantity}</p>
                )}
              </div>

              <div>
                <Label htmlFor="uom">
                  UOM <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="uom"
                  value={formData.uom}
                  onValueChange={(value) => handleSelectChange("uom", value)}
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.uom ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select UOM" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.uom.map((option, index) => (
                      <SelectItem key={`uom-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.uom && (
                  <p className="mt-1 text-xs text-red-500">{errors.uom}</p>
                )}
              </div>

              <div>
                <Label htmlFor="currentStock">
                  Current Stock As Per Factory{" "}
                  <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="currentStock"
                  type="text"
                  inputMode="decimal"
                  name="currentStock"
                  placeholder="Enter current stock"
                  value={formData.currentStock}
                  onChange={handleChange}
                  className={`mt-1 ${errors.currentStock ? "border-red-500" : ""}`}
                />
                {errors.currentStock && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.currentStock}
                  </p>
                )}
              </div>

              <div>
                <Label htmlFor="priority">
                  Priority <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="priority"
                  value={formData.priority}
                  onValueChange={(value) =>
                    handleSelectChange("priority", value)
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.priority ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select priority" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Regular">Regular</SelectItem>
                    <SelectItem value="Urgent">Urgent</SelectItem>
                    <SelectItem value="Planned">Planned</SelectItem>
                  </SelectContent>
                </Select>
                {errors.priority && (
                  <p className="mt-1 text-xs text-red-500">{errors.priority}</p>
                )}
              </div>

              <div>
                <Label htmlFor="typeOfIndent">
                  Type Of Indent <span className="text-red-500">*</span>
                </Label>
                <Select
                  name="typeOfIndent"
                  value={formData.typeOfIndent}
                  onValueChange={(value) =>
                    handleSelectChange("typeOfIndent", value)
                  }
                >
                  <SelectTrigger
                    className={`mt-1 ${errors.typeOfIndent ? "border-red-500" : ""}`}
                  >
                    <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent>
                    {dropdownOptions.indentType.map((option, index) => (
                      <SelectItem key={`type-${index}`} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.typeOfIndent && (
                  <p className="mt-1 text-xs text-red-500">
                    {errors.typeOfIndent}
                  </p>
                )}
              </div>

              {shouldShowDeliveryOrder && (
                <div className="lg:col-span-2">
                  <Label htmlFor="deliveryOrderNo">
                    Delivery Order No. <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="deliveryOrderNo"
                    type="text"
                    name="deliveryOrderNo"
                    placeholder="Enter delivery order number"
                    value={formData.deliveryOrderNo}
                    onChange={handleChange}
                    className="mt-1"
                  />
                </div>
              )}
            </div>

            <div className="lg:col-span-3">
              <Label htmlFor="notes">Notes</Label>
              <Textarea
                id="notes"
                name="notes"
                placeholder="Enter any additional notes or requirements"
                value={formData.notes}
                onChange={handleChange}
                className="min-h-[80px] mt-1"
              />
            </div>

            <div className="pt-4">
              <Button
                type="submit"
                className="w-full font-semibold rounded-md"
                disabled={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Submitting...
                  </>
                ) : (
                  "Generate Entry"
                )}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
