"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import {
  AlertTriangle,
  CheckCircle2,
  History,
  Info,
  Loader2,
  Search,
} from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useNotification } from "../context/NotificationContext";
import { supabase } from "../supabase";
import { useRealtime } from "../hooks/useRealtime";
import { canViewFirm } from "../utils/firmFilter";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  buildApprovedVendorUpdate,
  compareTechnicalTags,
  getVendorsFromRow,
} from "../utils/approvalVendorUtils";

const formatDateTime = (isoString) => {
  if (!isoString) return "-";
  const date = new Date(isoString);
  const day = date.getDate().toString().padStart(2, "0");
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const year = date.getFullYear();
  const hours = date.getHours().toString().padStart(2, "0");
  const minutes = date.getMinutes().toString().padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
};

const formatDate = (dateString) => {
  if (!dateString) return "-";
  const date = new Date(dateString);
  const day = date.getDate().toString().padStart(2, "0");
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const year = date.getFullYear();
  return `${day}/${month}/${year}`;
};

const getDelayDays = (expectedVendor, required) => {
  if (!expectedVendor || !required) return null;
  const d1 = new Date(expectedVendor);
  const d2 = new Date(required);
  d1.setHours(0, 0, 0, 0);
  d2.setHours(0, 0, 0, 0);
  const diffTime = d1 - d2;
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
};

const chemistryFields = [
  ["Al2O3", "alumina"],
  ["Fe2O3", "iron"],
  ["SiO2", "sio2"],
  ["CaO", "cao"],
  ["AP", "ap"],
  ["BD", "bd"],
];

const getTagTone = (tag) => {
  if (tag === "T1") return "bg-emerald-100 text-emerald-700";
  if (tag === "T2") return "bg-amber-100 text-amber-700";
  return "bg-slate-100 text-slate-700";
};

export default function ManagementApprovals() {
  const [pendingData, setPendingData] = useState([]);
  const [historyData, setHistoryData] = useState([]);
  const [filteredPendingData, setFilteredPendingData] = useState([]);
  const [filteredHistoryData, setFilteredHistoryData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [refreshData, setRefreshData] = useState(false);
  const [selectedIndent, setSelectedIndent] = useState(null);
  const [selectedVendorSlot, setSelectedVendorSlot] = useState("");
  const [openDialog, setOpenDialog] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [historySearchQuery, setHistorySearchQuery] = useState("");

  const { user } = useAuth();
  const { updateCount } = useNotification();

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const { data, error: fetchError } = await supabase
        .from("INDENT-PO")
        .select("*");

      if (fetchError) throw fetchError;

      let filteredData = data;
      if (user?.firmName) {
        filteredData = data.filter((row) =>
          canViewFirm(user.firmName, row["Firm Name"]),
        );
      }

      const pending = filteredData
        .filter(
          (row) =>
            row["Planned8"] !== null &&
            row["Planned8"] !== "" &&
            (!row["Actual8"] || row["Actual8"] === ""),
        )
        .map((row) => {
          const vendors = getVendorsFromRow(row)
            .filter((vendor) => vendor.technicalTag)
            .sort(compareTechnicalTags);

          return {
            id: row.id,
            indentId: row["Indent Id."] || "",
            firmName: row["Firm Name"] || "",
            indenter: row["Generated By"] || "",
            department: row["Type Of Indent"] || "",
            product: row["Material"] || "",
            planned8: row["Planned8"] || "",
            expectedRequirementDate: row["expected_requierment_date"] || "",
            vendors,
          };
        })
        .filter((item) => item.vendors.length > 0);

      const history = filteredData
        .filter((row) => row["Actual8"] !== null && row["Actual8"] !== "")
        .map((row) => {
          const vendors = getVendorsFromRow(row);
          const approvedVendor = vendors.find(
            (vendor) => vendor.name === (row["Approved Vendor Name"] || ""),
          );

          return {
            id: row.id,
            indentId: row["Indent Id."] || "",
            firmName: row["Firm Name"] || "",
            indenter: row["Generated By"] || "",
            department: row["Type Of Indent"] || "",
            product: row["Material"] || "",
            actual8: row["Actual8"] || "",
            approvedVendorName: row["Approved Vendor Name"] || "",
            approvedRate: row["Approved Rate"] || "0",
            approvedTag: approvedVendor?.technicalTag || "",
          };
        })
        .sort((a, b) => new Date(b.actual8) - new Date(a.actual8));

      setPendingData(pending);
      setFilteredPendingData(pending);
      setHistoryData(history);
      setFilteredHistoryData(history);
      updateCount("management", pending.length);
    } catch (err) {
      console.error("Error fetching management approvals:", err);
      setError(err.message || "Failed to load management approvals");
      toast.error("Failed to load management approvals", {
        description: err.message,
      });
    } finally {
      setLoading(false);
    }
  }, [updateCount, user]);

  useEffect(() => {
    fetchData();
  }, [fetchData, refreshData]);

  // Realtime: Listen for changes in INDENT-PO and refresh
  useRealtime("INDENT-PO", () => {
    setRefreshData((prev) => !prev);
  });


  useEffect(() => {
    const query = searchQuery.trim().toLowerCase();
    setFilteredPendingData(
      pendingData.filter(
        (item) =>
          item.indentId.toLowerCase().includes(query) ||
          item.firmName.toLowerCase().includes(query) ||
          item.product.toLowerCase().includes(query) ||
          item.vendors.some((vendor) =>
            vendor.name.toLowerCase().includes(query),
          ),
      ),
    );
  }, [pendingData, searchQuery]);

  useEffect(() => {
    const query = historySearchQuery.trim().toLowerCase();
    setFilteredHistoryData(
      historyData.filter(
        (item) =>
          item.indentId.toLowerCase().includes(query) ||
          item.firmName.toLowerCase().includes(query) ||
          item.product.toLowerCase().includes(query) ||
          item.approvedVendorName.toLowerCase().includes(query) ||
          item.approvedTag.toLowerCase().includes(query),
      ),
    );
  }, [historyData, historySearchQuery]);

  const selectedVendor = useMemo(
    () =>
      selectedIndent?.vendors.find(
        (vendor) => vendor.slot.toString() === selectedVendorSlot,
      ) || null,
    [selectedIndent, selectedVendorSlot],
  );

  const onApprove = async () => {
    if (!selectedIndent || !selectedVendor) {
      toast.error("Please select one vendor");
      return;
    }

    setIsSubmitting(true);
    try {
      const { error: updateError } = await supabase
        .from("INDENT-PO")
        .update({
          ...buildApprovedVendorUpdate(selectedVendor),
          "Approved Date": new Date().toISOString(),
          Actual8: new Date().toISOString(),
          Planned2: new Date().toISOString(),
          "Have To Make PO": "Yes",
        })
        .eq("id", selectedIndent.id);

      if (updateError) throw updateError;

      toast.success(`Management approved ${selectedIndent.indentId}`);
      setOpenDialog(false);
      setSelectedIndent(null);
      setSelectedVendorSlot("");
      setRefreshData((prev) => !prev);
    } catch (error) {
      console.error("Error completing management approval:", error);
      toast.error("Management approval failed", {
        description: error.message,
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Card className="w-full max-w-full mx-auto bg-white border border-gray-200 rounded-lg shadow-md">
      <CardHeader className="p-4 border-b border-gray-200">
        <CardTitle className="flex items-center gap-2 text-lg text-gray-800">
          <CheckCircle2 className="h-5 w-5 text-[#7da23a]" />
          Management Final Approval
        </CardTitle>
        <CardDescription className="text-sm text-gray-500">
          Review the factory technical tags and approve one final vendor.
        </CardDescription>
        {user?.firmName && (
          <p className="border-t border-gray-100 mt-2 pt-2 text-[#7da23a] text-xs font-medium">
            Showing data for: {" "}
            <span className="font-bold">
              {user.firmName === "all"
                ? "All Firms"
                : Array.isArray(user.firmName)
                  ? user.firmName.join(", ")
                  : user.firmName}
            </span>
          </p>
        )}
      </CardHeader>

      <CardContent className="p-4">
        <Tabs defaultValue="pending">
          <TabsList className="mb-4">
            <TabsTrigger value="pending" className="gap-2">
              Pending <Badge variant="secondary">{pendingData.length}</Badge>
            </TabsTrigger>
            <TabsTrigger value="history" className="gap-2">
              History <Badge variant="secondary">{historyData.length}</Badge>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="pending" className="space-y-4">
            <div className="relative">
              <Search className="absolute w-4 h-4 text-gray-400 -translate-y-1/2 left-3 top-1/2" />
              <Input
                className="pl-9"
                placeholder="Search indent, firm, vendor..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>

            {loading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-6 w-6 animate-spin text-[#7da23a]" />
              </div>
            ) : error ? (
              <div className="p-6 text-center border border-red-200 rounded-xl bg-red-50">
                <AlertTriangle className="w-10 h-10 mx-auto mb-3 text-red-500" />
                <p className="font-medium text-red-700">{error}</p>
              </div>
            ) : filteredPendingData.length === 0 ? (
              <div className="py-12 text-center border border-gray-200 border-dashed rounded-xl">
                <Info className="w-10 h-10 mx-auto mb-3 text-gray-300" />
                <p className="text-sm text-gray-500">
                  No pending management approvals.
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto border border-gray-200 rounded-xl">
                <Table>
                  <TableHeader className="bg-gray-50">
                    <TableRow>
                      <TableHead>Action</TableHead>
                      <TableHead>Indent</TableHead>
                      <TableHead>Firm</TableHead>
                      <TableHead>Product</TableHead>
                      <TableHead>Required On</TableHead>
                      <TableHead>Timeline Info</TableHead>
                      <TableHead>Tagged Vendors</TableHead>
                      <TableHead>Factory Done</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredPendingData.map((item) => (
                      <TableRow key={item.id}>
                        <TableCell>
                          <Button
                            className="bg-[#7da23a] hover:bg-[#6b8e2f]"
                            onClick={() => {
                              setSelectedIndent(item);
                              setSelectedVendorSlot("");
                              setOpenDialog(true);
                            }}
                          >
                            Review
                          </Button>
                        </TableCell>
                        <TableCell className="font-medium">
                          {item.indentId}
                        </TableCell>
                        <TableCell>{item.firmName}</TableCell>
                        <TableCell>{item.product}</TableCell>
                        <TableCell className="text-xs font-medium text-blue-600">
                          {formatDate(item.expectedRequirementDate)}
                        </TableCell>
                        <TableCell>
                          {(() => {
                            const delays = item.vendors
                              .map(v => getDelayDays(v.expectedDate, item.expectedRequirementDate))
                              .filter(d => d !== null);
                            const minDelay = Math.min(...delays);
                            
                            if (delays.length === 0) return <span className="text-gray-400">-</span>;
                            
                            return (
                              <Badge className={`text-[10px] ${minDelay > 0 ? "bg-red-100 text-red-700" : "bg-green-100 text-green-700"}`}>
                                {minDelay > 0 ? `${minDelay}d Delay` : "On Time"}
                              </Badge>
                            );
                          })()}
                        </TableCell>
                        <TableCell>
                          <div className="flex flex-wrap gap-1.5 focus-within:z-10">
                            {item.vendors.map((vendor) => (
                              <Badge
                                key={vendor.slot}
                                className={`${getTagTone(vendor.technicalTag)} px-1.5 py-0.5 text-[10px]`}
                              >
                                {vendor.technicalTag} · {vendor.name.split(' ').slice(0, 2).join(' ')}
                              </Badge>
                            ))}
                          </div>
                        </TableCell>
                        <TableCell className="text-[10px] text-gray-500 whitespace-nowrap">{formatDateTime(item.planned8)}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </TabsContent>

          <TabsContent value="history" className="space-y-4">
            <div className="relative">
              <Search className="absolute w-4 h-4 text-gray-400 -translate-y-1/2 left-3 top-1/2" />
              <Input
                className="pl-9"
                placeholder="Search approved history..."
                value={historySearchQuery}
                onChange={(e) => setHistorySearchQuery(e.target.value)}
              />
            </div>

            {loading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-6 w-6 animate-spin text-[#7da23a]" />
              </div>
            ) : filteredHistoryData.length === 0 ? (
              <div className="py-12 text-center border border-gray-200 border-dashed rounded-xl">
                <Info className="w-10 h-10 mx-auto mb-3 text-gray-300" />
                <p className="text-sm text-gray-500">
                  No management approval history yet.
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto border border-gray-200 rounded-xl">
                <Table>
                  <TableHeader className="bg-gray-50">
                    <TableRow>
                      <TableHead>Indent</TableHead>
                      <TableHead>Firm</TableHead>
                      <TableHead>Product</TableHead>
                      <TableHead>Approved Vendor</TableHead>
                      <TableHead>Tag</TableHead>
                      <TableHead>Rate</TableHead>
                      <TableHead>Approved On</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredHistoryData.map((item) => (
                      <TableRow key={item.id}>
                        <TableCell>{item.indentId}</TableCell>
                        <TableCell>{item.firmName}</TableCell>
                        <TableCell>{item.product}</TableCell>
                        <TableCell>{item.approvedVendorName}</TableCell>
                        <TableCell>
                          {item.approvedTag ? (
                            <Badge className={getTagTone(item.approvedTag)}>
                              {item.approvedTag}
                            </Badge>
                          ) : (
                            "-"
                          )}
                        </TableCell>
                        <TableCell className="font-semibold">
                          ₹{item.approvedRate}
                        </TableCell>
                        <TableCell>{formatDateTime(item.actual8)}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </TabsContent>
        </Tabs>
      </CardContent>

      <Dialog
        open={openDialog}
        onOpenChange={(open) => {
          setOpenDialog(open);
          if (!open) {
            setSelectedIndent(null);
            setSelectedVendorSlot("");
          }
        }}
      >
        <DialogContent className="sm:max-w-[1100px]">
          {selectedIndent && (
            <>
              <DialogHeader>
                <DialogTitle>Management Vendor Review</DialogTitle>
                <DialogDescription className="flex items-center flex-wrap">
                  Review tagged vendors and approve one for{" "}
                  <span className="font-bold text-gray-900 mx-1">{selectedIndent.indentId}</span>
                  {" "}at{" "}
                  <Badge variant="outline" className="ml-2 bg-amber-50 text-amber-800 border-amber-200 font-bold px-3 py-1 shadow-sm">
                    {selectedIndent.firmName}
                  </Badge>
                </DialogDescription>
              </DialogHeader>

              <div className="grid gap-4 py-2 lg:grid-cols-3">
                {selectedIndent.vendors.map((vendor) => {
                  const isSelected =
                    selectedVendorSlot === vendor.slot.toString();

                  return (
                    <button
                      key={vendor.slot}
                      type="button"
                      onClick={() =>
                        setSelectedVendorSlot(vendor.slot.toString())
                      }
                      className={`rounded-2xl border p-4 text-left transition ${
                        isSelected
                          ? "border-[#7da23a] bg-green-50 shadow-sm"
                          : "border-gray-200 bg-white hover:border-gray-300"
                      }`}
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <Badge className={getTagTone(vendor.technicalTag)}>
                            {vendor.technicalTag}
                          </Badge>
                          <p className="mt-3 text-base font-semibold text-gray-900">
                            {vendor.name}
                          </p>
                          <p className="mt-1 text-sm text-gray-500">
                            {vendor.paymentTerm || "Payment term not set"}
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="text-2xl font-bold text-gray-900">
                            ₹{vendor.rate}
                          </p>
                          <p className="text-xs text-gray-500">
                            {vendor.rateType}
                          </p>
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-3 p-3 mt-4 text-xs text-gray-600 rounded-xl bg-slate-50">
                        <div>
                          <span className="block text-[10px] uppercase tracking-wide text-gray-400">
                            Packaging
                          </span>
                          <span>{vendor.packaging || "-"}</span>
                        </div>
                        <div>
                          <span className="block text-[10px] uppercase tracking-wide text-gray-400">
                            Quote
                          </span>
                          <span>{vendor.quotationNumber || "-"}</span>
                        </div>
                        <div>
                          <span className="block text-[10px] uppercase tracking-wide text-gray-400">
                            Quote Date
                          </span>
                          <span>{vendor.quotationDate || "-"}</span>
                        </div>
                        <div>
                          <span className="block text-[10px] uppercase tracking-wide text-gray-400">
                            Advance
                          </span>
                          <span>
                            {vendor.advancePercentage
                              ? `${vendor.advancePercentage}%`
                              : "-"}
                          </span>
                        </div>
                        <div className="col-span-2 mt-2 pt-2 border-t border-slate-200">
                          <span className="block text-[10px] uppercase tracking-wide text-gray-400 mb-1">
                            Delivery Timeline
                          </span>
                          <div className="flex items-center justify-between">
                            <div>
                              <p className="text-[10px] text-gray-500">Requirement</p>
                              <p className="font-medium">{formatDate(selectedIndent.expectedRequirementDate)}</p>
                            </div>
                            <div className="text-right">
                              <p className="text-[10px] text-gray-500">Vendor Commit</p>
                              <p className="font-medium text-blue-600">{formatDate(vendor.expectedDate)}</p>
                            </div>
                          </div>
                          {getDelayDays(vendor.expectedDate, selectedIndent.expectedRequirementDate) !== null && (
                            <div className={`mt-2 text-center py-1 rounded text-[10px] font-bold uppercase ${
                              getDelayDays(vendor.expectedDate, selectedIndent.expectedRequirementDate) > 0
                                ? "bg-red-50 text-red-600"
                                : "bg-green-50 text-green-600"
                            }`}>
                              {getDelayDays(vendor.expectedDate, selectedIndent.expectedRequirementDate) > 0
                                ? `${getDelayDays(vendor.expectedDate, selectedIndent.expectedRequirementDate)} Days Delay`
                                : "On Time / Early"}
                            </div>
                          )}
                        </div>
                      </div>

                      <div className="p-3 mt-4 border border-gray-200 border-dashed rounded-xl">
                        <p className="mb-2 text-xs font-semibold text-gray-600">
                          Chemical Details
                        </p>
                        <div className="grid grid-cols-3 gap-y-2 text-[11px] text-gray-600">
                          {chemistryFields.map(([label, key]) => (
                            <div key={key}>
                              <span className="block text-[10px] text-gray-400">
                                {label}
                              </span>
                              <span>{vendor[key] || "-"}</span>
                            </div>
                          ))}
                          <div className="col-span-3">
                            <span className="block text-[10px] text-gray-400">
                              Fineness
                            </span>
                            <span>{vendor.fineness || "-"}</span>
                          </div>
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>

              <DialogFooter>
                <Button variant="outline" onClick={() => setOpenDialog(false)}>
                  Cancel
                </Button>
                <Button
                  className="bg-[#7da23a] hover:bg-[#6b8e2f]"
                  onClick={onApprove}
                  disabled={!selectedVendorSlot || isSubmitting}
                >
                  {isSubmitting ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : null}
                  Approve Selected Vendor
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>
    </Card>
  );
}
