"use client";

import { useState, useEffect, useCallback } from "react";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  CheckCircle2,
  History,
  Loader2,
  AlertTriangle,
  Info,
  Users,
  Search,
} from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useNotification } from "../context/NotificationContext";
import { supabase } from "../supabase";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog";

// Helper function to format datetime
const formatDateTime = (isoString) => {
  if (!isoString) return "-";
  const date = new Date(isoString);
  const day = date.getDate().toString().padStart(2, "0");
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const year = date.getFullYear();
  const hours = date.getHours().toString().padStart(2, "0");
  const minutes = date.getMinutes().toString().padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
};

export default function ManagementApprovals() {
  const [pendingData, setPendingData] = useState([]);
  const [historyData, setHistoryData] = useState([]);
  const [filteredPendingData, setFilteredPendingData] = useState([]);
  const [filteredHistoryData, setFilteredHistoryData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [refreshData, setRefreshData] = useState(false);
  const [selectedIndent, setSelectedIndent] = useState(null);
  const [openDialog, setOpenDialog] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [historySearchQuery, setHistorySearchQuery] = useState("");

  const { user } = useAuth();
  const { updateCount } = useNotification();

  // Fetch data from Supabase
  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const { data, error: fetchError } = await supabase
        .from("INDENT-PO")
        .select("*");

      if (fetchError) throw fetchError;

      // Filter by firm name
      let filteredData = data;
      if (user?.firmName && user.firmName.toLowerCase() !== "all") {
        filteredData = data.filter(
          (row) =>
            row["Firm Name"] &&
            String(row["Firm Name"]).toLowerCase() ===
              user.firmName.toLowerCase(),
        );
      }

      // Process pending data (Planned8 is not null and Actual8 is null)
      const pending = filteredData
        .filter(
          (row) =>
            row["Planned8"] !== null &&
            row["Planned8"] !== "" &&
            (!row["Actual8"] || row["Actual8"] === ""),
        )
        .map((row) => ({
          id: row.id,
          indentId: row["Indent Id."] || "",
          firmName: row["Firm Name"] || "",
          indenter: row["Generated By"] || "",
          department: row["Type Of Indent"] || "",
          product: row["Material"] || "",
          planned8: row["Planned8"] || "",
          vendor: row["Approved Vendor Name"] || "",
          rate: row["Approved Rate"] || "0",
          paymentTerm: row["Approved Payment Term"] || "",
          packaging: row["Packaging"] || "",
          taxType: row["Select Rate Type 1"] || "", // Reusing rate type from original
          comparisonSheet: row["Comparison Sheet"] || "",
        }));

      // Process history data (Actual8 is not null)
      const history = filteredData
        .filter(
          (row) =>
            row["Actual8"] !== null &&
            row["Actual8"] !== "",
        )
        .map((row) => ({
          id: row.id,
          indentId: row["Indent Id."] || "",
          firmName: row["Firm Name"] || "",
          indenter: row["Generated By"] || "",
          product: row["Material"] || "",
          actual8: row["Actual8"] || "",
          vendor: row["Approved Vendor Name"] || "",
          rate: row["Approved Rate"] || "0",
        }))
        .sort((a, b) => new Date(b.actual8) - new Date(a.actual8));

      setPendingData(pending);
      setFilteredPendingData(pending);
      setHistoryData(history);
      setFilteredHistoryData(history);

      // Update notification count for management channel
      updateCount("management", pending.length);
    } catch (err) {
      console.error("Error fetching management data:", err);
      setError("Failed to load data: " + err.message);
      toast.error("Failed to load data");
    } finally {
      setLoading(false);
    }
  }, [user, updateCount]);

  useEffect(() => {
    fetchData();
  }, [fetchData, refreshData]);

  // Filters logic
  useEffect(() => {
    const query = searchQuery.toLowerCase();
    setFilteredPendingData(
      pendingData.filter(
        (item) =>
          item.indentId.toLowerCase().includes(query) ||
          item.firmName.toLowerCase().includes(query) ||
          item.product.toLowerCase().includes(query) ||
          item.vendor.toLowerCase().includes(query)
      )
    );
  }, [searchQuery, pendingData]);

  useEffect(() => {
    const query = historySearchQuery.toLowerCase();
    setFilteredHistoryData(
      historyData.filter(
        (item) =>
          item.indentId.toLowerCase().includes(query) ||
          item.firmName.toLowerCase().includes(query) ||
          item.product.toLowerCase().includes(query) ||
          item.vendor.toLowerCase().includes(query)
      )
    );
  }, [historySearchQuery, historyData]);

  async function onApprove() {
    if (!selectedIndent) return;

    setIsSubmitting(true);
    try {
      const { error: updateError } = await supabase
        .from("INDENT-PO")
        .update({
          Actual8: new Date().toISOString(),
          Planned2: new Date().toISOString(), // Trigger PO Generation
          "Have To Make PO": "Yes" // Ensure it shows up in PO tab
        })
        .eq("id", selectedIndent.id);

      if (updateError) throw updateError;

      toast.success(`Management approved ${selectedIndent.indentId}`);
      setOpenDialog(false);
      setRefreshData((p) => !p);
    } catch (error) {
      console.error("Error in management approval:", error);
      toast.error("Approval failed");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Card className="w-full max-w-full mx-auto bg-white border-gray-200">
      <CardHeader className="p-4 border-b">
        <CardTitle className="flex items-center gap-2 text-lg text-gray-800">
          <CheckCircle2 className="h-5 w-5 text-[#7da23a]" />
          Management Final Approval
        </CardTitle>
        <CardDescription>
          Final decision layer for factory-approved vendors
        </CardDescription>
      </CardHeader>

      <CardContent className="p-4">
        <Tabs defaultValue="pending">
          <TabsList className="mb-4">
            <TabsTrigger value="pending" className="gap-2">
              Pending <Badge variant="secondary">{pendingData.length}</Badge>
            </TabsTrigger>
            <TabsTrigger value="history" className="gap-2">
              History <Badge variant="secondary">{historyData.length}</Badge>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="pending">
            <div className="mb-4 flex gap-2">
              <div className="relative flex-1">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500" />
                <Input
                  placeholder="Search indents..."
                  className="pl-9"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
              </div>
            </div>

            {loading ? (
              <div className="flex justify-center p-8"><Loader2 className="animate-spin" /></div>
            ) : filteredPendingData.length === 0 ? (
              <div className="text-center p-8 text-gray-500">No pending management approvals</div>
            ) : (
              <div className="rounded-md border overflow-x-auto">
                <Table>
                  <TableHeader className="bg-gray-50">
                    <TableRow>
                      <TableHead>Indent ID</TableHead>
                      <TableHead>Firm</TableHead>
                      <TableHead>Product</TableHead>
                      <TableHead>Approved Vendor</TableHead>
                      <TableHead>Approved Rate</TableHead>
                      <TableHead>Factory Approved On</TableHead>
                      <TableHead className="text-right">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredPendingData.map((item) => (
                      <TableRow key={item.id}>
                        <TableCell className="font-medium">{item.indentId}</TableCell>
                        <TableCell>{item.firmName}</TableCell>
                        <TableCell>{item.product}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className="border-[#7da23a] text-[#7da23a]">
                            {item.vendor}
                          </Badge>
                        </TableCell>
                        <TableCell className="font-bold text-gray-900">₹{item.rate}</TableCell>
                        <TableCell>{formatDateTime(item.planned8)}</TableCell>
                        <TableCell className="text-right">
                          <Button
                            size="sm"
                            className="bg-[#7da23a] hover:bg-[#6b8e2f]"
                            onClick={() => {
                              setSelectedIndent(item);
                              setOpenDialog(true);
                            }}
                          >
                            Review & Approve
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </TabsContent>

          <TabsContent value="history">
             {/* History Table implementation similar to pending but for approved items */}
             <div className="rounded-md border overflow-x-auto">
                <Table>
                  <TableHeader className="bg-gray-50">
                    <TableRow>
                      <TableHead>Indent ID</TableHead>
                      <TableHead>Firm</TableHead>
                      <TableHead>Product</TableHead>
                      <TableHead>Approved Vendor</TableHead>
                      <TableHead>Final Rate</TableHead>
                      <TableHead>Management Approved On</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredHistoryData.map((item) => (
                      <TableRow key={item.id}>
                        <TableCell>{item.indentId}</TableCell>
                        <TableCell>{item.firmName}</TableCell>
                        <TableCell>{item.product}</TableCell>
                        <TableCell>{item.vendor}</TableCell>
                        <TableCell className="font-bold">₹{item.rate}</TableCell>
                        <TableCell>{formatDateTime(item.actual8)}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
          </TabsContent>
        </Tabs>
      </CardContent>

      <Dialog open={openDialog} onOpenChange={setOpenDialog}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>Management Approval Review</DialogTitle>
            <DialogDescription>
              Confirm the final approval for procurement
            </DialogDescription>
          </DialogHeader>
          
          {selectedIndent && (
            <div className="space-y-4 py-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="p-3 bg-gray-50 rounded-lg">
                  <span className="block text-xs text-gray-500 uppercase font-bold mb-1">Indent</span>
                  <span className="font-medium">{selectedIndent.indentId}</span>
                </div>
                <div className="p-3 bg-gray-50 rounded-lg">
                  <span className="block text-xs text-gray-500 uppercase font-bold mb-1">Product</span>
                  <span className="font-medium">{selectedIndent.product}</span>
                </div>
                <div className="col-span-2 p-4 border-2 border-[#7da23a]/20 bg-[#7da23a]/5 rounded-xl">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-xs text-gray-500 uppercase font-bold">Approved Vendor</span>
                    <Badge className="bg-[#7da23a]">{selectedIndent.vendor}</Badge>
                  </div>
                  <div className="flex justify-between items-baseline">
                    <span className="text-xs text-gray-500 uppercase font-bold">Approved Rate</span>
                    <span className="text-2xl font-black text-gray-900">₹{selectedIndent.rate}</span>
                  </div>
                </div>
                <div className="p-3 bg-gray-50 rounded-lg">
                    <span className="block text-xs text-gray-500 uppercase font-bold mb-1">Payment Term</span>
                    <span className="text-xs">{selectedIndent.paymentTerm || "-"}</span>
                </div>
                <div className="p-3 bg-gray-50 rounded-lg">
                    <span className="block text-xs text-gray-500 uppercase font-bold mb-1">Packaging</span>
                    <span className="text-xs">{selectedIndent.packaging || "-"}</span>
                </div>
              </div>
              
              {selectedIndent.comparisonSheet && (
                <div className="pt-2">
                  <Button variant="outline" className="w-full text-xs" asChild>
                    <a href={selectedIndent.comparisonSheet} target="_blank" rel="noreferrer">
                      View Comparison Sheet
                    </a>
                  </Button>
                </div>
              )}
            </div>
          )}

          <DialogFooter className="gap-2 sm:gap-0">
            <DialogClose asChild>
              <Button variant="outline">Cancel</Button>
            </DialogClose>
            <Button 
              className="bg-[#7da23a] hover:bg-[#6b8e2f]"
              onClick={onApprove}
              disabled={isSubmitting}
            >
              {isSubmitting ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : null}
              Confirm Management Approval
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
