"use client";
import { useState, useEffect, useMemo, useContext, useCallback } from "react";
import {
  Loader2,
  AlertTriangle,
  TrendingDown,
  DollarSign,
  Package,
  Info,
  Filter,
  ExternalLink,
  Beaker,
  Edit,
  Eye,
  FileText,
  AlertCircle,
  RefreshCw,
  Save,
  X,
  History,
} from "lucide-react";
import { MixerHorizontalIcon } from "@radix-ui/react-icons";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Checkbox } from "@/components/ui/checkbox";
import { AuthContext } from "../context/AuthContext";
import { toast } from "sonner";
import { supabase } from "../supabase";

// Rate Mismatch Columns Meta - ALL LIFT-ACCOUNTS + INDENT-PO columns
const RATE_MISMATCH_COLUMNS_META = [
  // Core mismatch fields
  { header: "Actions", dataKey: "actions", toggleable: false, alwaysVisible: true },

  { header: "Lift ID", dataKey: "id", toggleable: true, alwaysVisible: true },
  { header: "Indent Number", dataKey: "indentNo", toggleable: true },
  { header: "Material Rate (Lift)", dataKey: "materialRate", toggleable: true },
  { header: "PO Rate (Original)", dataKey: "poRate", toggleable: true },
  { header: "Rate Difference", dataKey: "rateDifference", toggleable: true },

  // ALL LIFT-ACCOUNTS columns (excluding Planned/Actual/Delay - columns 19-21, 29-31, 34-36, 52-54)
  { header: "Date", dataKey: "timestamp", toggleable: true },
  { header: "Firm Name", dataKey: "firmName", toggleable: true },
  { header: "Party Name", dataKey: "vendorName", toggleable: true },
  { header: "Product Name", dataKey: "material", toggleable: true },
  { header: "Qty", dataKey: "quantity", toggleable: true },
  { header: "Area Lifting", dataKey: "areaLifting", toggleable: true },
  { header: "Truck No.", dataKey: "truckNo", toggleable: true },
  { header: "Transporter", dataKey: "transporterName", toggleable: true },
  { header: "Bill No.", dataKey: "billNo", toggleable: true },
  { header: "Type", dataKey: "liftType", toggleable: true },
  { header: "Bilty No.", dataKey: "biltyNo", toggleable: true },
  { header: "Type Of Rate", dataKey: "typeOfTransportingRate", toggleable: true },
  { header: "Rate", dataKey: "materialRate", toggleable: true },
  { header: "Truck Qty", dataKey: "truckQty", toggleable: true },
  { header: "Bill Image", dataKey: "billImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Bilty Image", dataKey: "biltyImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Weight Slip", dataKey: "weightSlipImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Qty Diff Status", dataKey: "qtyDifferenceStatus", toggleable: true },
  { header: "Diff Qty", dataKey: "differenceQty", toggleable: true },
  { header: "Total Freight", dataKey: "totalFreight", toggleable: true },
  { header: "Status", dataKey: "status", toggleable: true },
  { header: "Driver No.", dataKey: "driverNo", toggleable: true },
  { header: "Lead Time", dataKey: "leadTimeToFactory", toggleable: true },
  { header: "Lifting Qty", dataKey: "liftingQty", toggleable: true },
  { header: "Date Received", dataKey: "dateOfReceiving", toggleable: true },
  { header: "Bill Qty", dataKey: "totalBillQuantity", toggleable: true },
  { header: "Actual Qty", dataKey: "actualQuantity", toggleable: true },
  { header: "Moisture", dataKey: "moisture", toggleable: true },
  { header: "Alumina %", dataKey: "aluminaPercent", toggleable: true },
  { header: "Iron %", dataKey: "ironPercent", toggleable: true },

  // ALL INDENT-PO columns (excluding Planned/Actual/Delay and duplicates)
  { header: "PO Timestamp", dataKey: "poTimestamp", toggleable: true },
  { header: "Indent Id", dataKey: "indentId", toggleable: true },
  { header: "Firm Name (PO)", dataKey: "poFirmName", toggleable: true },
  { header: "Generated By", dataKey: "poGeneratedBy", toggleable: true },
  { header: "Vendor (PO)", dataKey: "poVendor", toggleable: true },
  { header: "Material (PO)", dataKey: "poMaterial", toggleable: true },
  { header: "Quantity (PO)", dataKey: "poQuantity", toggleable: true },
  { header: "Current Stock", dataKey: "poCurrentStock", toggleable: true },
  { header: "Priority", dataKey: "poPriority", toggleable: true },
  { header: "Delivery Order No.", dataKey: "poDeliveryOrderNo", toggleable: true },
  { header: "Notes (PO)", dataKey: "poNotes", toggleable: true },
  { header: "Approved Qty", dataKey: "poApprovedQty", toggleable: true },
  { header: "Approval Status", dataKey: "poApprovalStatus", toggleable: true },
  { header: "Remarks (PO)", dataKey: "poRemarks", toggleable: true },
  { header: "Have To Make PO", dataKey: "poHaveToMake", toggleable: true },
  { header: "Rate (PO)", dataKey: "poRate", toggleable: true },
  { header: "Lead Time (days)", dataKey: "poLeadTime", toggleable: true },
  { header: "Total Quantity (PO)", dataKey: "poTotalQuantity", toggleable: true },
  { header: "Total Amount", dataKey: "poTotalAmount", toggleable: true },
  { header: "PO Copy", dataKey: "poCopyUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Advance To Be Paid", dataKey: "poAdvanceToBePaid", toggleable: true },
  { header: "To Be Paid Amount", dataKey: "poToBePaidAmount", toggleable: true },
  { header: "When To Be Paid", dataKey: "poWhenToBePaid", toggleable: true },
  { header: "PO Notes", dataKey: "poPONotes", toggleable: true },
  { header: "Alumina % (PO)", dataKey: "poAluminaPercent", toggleable: true },
  { header: "Iron % (PO)", dataKey: "poIronPercent", toggleable: true },
  { header: "Total Lifted", dataKey: "poTotalLifted", toggleable: true },
  { header: "Pending Qty", dataKey: "poPendingQty", toggleable: true },
  // { header: "Order Cancel Qty", dataKey: "poOrderCancelQty", toggleable: true },
  // { header: "Status (PO)", dataKey: "poStatus", toggleable: true },

];

// Quantity Mismatch Columns Meta - ALL LIFT-ACCOUNTS + INDENT-PO columns
const QUANTITY_MISMATCH_COLUMNS_META = [
  // Core mismatch fields
  { header: "Lift Number", dataKey: "liftNo", toggleable: true, alwaysVisible: true },
  { header: "PO Number", dataKey: "indentNo", toggleable: true },
  { header: "Firm Name", dataKey: "firmName", toggleable: true },
  { header: "Party Name", dataKey: "vendorName", toggleable: true },
  { header: "Product Name", dataKey: "rawMaterialName", toggleable: true },
  { header: "Lifted Qty (Column J)", dataKey: "liftedQty", toggleable: true },
  { header: "Actual Quantity (Column Y)", dataKey: "actualQuantityY", toggleable: true },
  { header: "Weight Slip Qty (Column BF)", dataKey: "weightSlipQty", toggleable: true },
  { header: "Quantity Difference", dataKey: "qtyDifference", toggleable: true },

  // Additional LIFT-ACCOUNTS columns
  { header: "Date", dataKey: "timestamp", toggleable: true },
  { header: "Firm Name", dataKey: "firmName", toggleable: true },
  { header: "Party Name", dataKey: "vendorName", toggleable: true },
  { header: "Product Name", dataKey: "rawMaterialName", toggleable: true },
  { header: "Qty", dataKey: "quantity", toggleable: true },
  { header: "Area Lifting", dataKey: "areaLifting", toggleable: true },
  { header: "Truck No.", dataKey: "truckNo", toggleable: true },
  { header: "Transporter", dataKey: "transporterName", toggleable: true },
  { header: "Bill No.", dataKey: "billNo", toggleable: true },
  { header: "Type", dataKey: "liftType", toggleable: true },
  { header: "Bilty No.", dataKey: "biltyNo", toggleable: true },
  { header: "Type Of Rate", dataKey: "typeOfTransportingRate", toggleable: true },
  { header: "Rate", dataKey: "materialRate", toggleable: true },
  { header: "Truck Qty", dataKey: "truckQty", toggleable: true },
  { header: "Bill Image", dataKey: "billImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Bilty Image", dataKey: "biltyImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Weight Slip", dataKey: "weightSlipImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Qty Diff Status", dataKey: "qtyDifferenceStatus", toggleable: true },
  { header: "Diff Qty", dataKey: "differenceQty", toggleable: true },
  { header: "Total Freight", dataKey: "totalFreight", toggleable: true },
  { header: "Status", dataKey: "status", toggleable: true },

  // INDENT-PO columns
  { header: "PO Timestamp", dataKey: "poTimestamp", toggleable: true },
  { header: "Generated By", dataKey: "poGeneratedBy", toggleable: true },
  { header: "Quantity (PO)", dataKey: "poQuantity", toggleable: true },
  { header: "Current Stock", dataKey: "poCurrentStock", toggleable: true },
  { header: "Priority", dataKey: "poPriority", toggleable: true },
  { header: "Delivery Order No.", dataKey: "poDeliveryOrderNo", toggleable: true },
  { header: "Notes (PO)", dataKey: "poNotes", toggleable: true },
  { header: "Approved Qty", dataKey: "poApprovedQty", toggleable: true },
  { header: "Approval Status", dataKey: "poApprovalStatus", toggleable: true },
  { header: "Have To Make PO", dataKey: "poHaveToMake", toggleable: true },
  { header: "Rate (PO)", dataKey: "poRate", toggleable: true },
  { header: "Lead Time (days)", dataKey: "poLeadTime", toggleable: true },
  { header: "Total Quantity (PO)", dataKey: "poTotalQuantity", toggleable: true },
  { header: "Total Amount", dataKey: "poTotalAmount", toggleable: true },
  { header: "PO Copy", dataKey: "poCopyUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Advance To Be Paid", dataKey: "poAdvanceToBePaid", toggleable: true },
  { header: "To Be Paid Amount", dataKey: "poToBePaidAmount", toggleable: true },
  { header: "When To Be Paid", dataKey: "poWhenToBePaid", toggleable: true },
  { header: "PO Notes", dataKey: "poPONotes", toggleable: true },
  { header: "Alumina % (PO)", dataKey: "poAluminaPercent", toggleable: true },
  { header: "Iron % (PO)", dataKey: "poIronPercent", toggleable: true },
  { header: "Total Lifted (PO)", dataKey: "poTotalLifted", toggleable: true },
  { header: "Pending Qty (PO)", dataKey: "poPendingQty", toggleable: true },
  { header: "Order Cancel Qty", dataKey: "poOrderCancelQty", toggleable: true },
  { header: "Status (PO)", dataKey: "poStatus", toggleable: true },

  { header: "Actions", dataKey: "actions", toggleable: false, alwaysVisible: true },
];

// Material Properties Mismatch Columns Meta - ALL LIFT-ACCOUNTS + INDENT-PO + TL columns
const MATERIAL_MISMATCH_COLUMNS_META = [
  // Core mismatch fields
  { header: "Lift Number", dataKey: "liftNo", toggleable: true, alwaysVisible: true },
  { header: "Raw Material", dataKey: "rawMaterial", toggleable: true },
  { header: "Firm Name", dataKey: "firmName", toggleable: true },
  { header: "TL Alumina %", dataKey: "tlAlumina", toggleable: true },
  { header: "Lift Alumina %", dataKey: "liftAlumina", toggleable: true },
  { header: "Alumina Diff", dataKey: "aluminaDiff", toggleable: true },
  { header: "TL Iron %", dataKey: "tlIron", toggleable: true },
  { header: "Lift Iron %", dataKey: "liftIron", toggleable: true },
  { header: "Iron Diff", dataKey: "ironDiff", toggleable: true },
  { header: "TL AP", dataKey: "tlAP", toggleable: true },
  { header: "Lift AP", dataKey: "liftAP", toggleable: true },
  { header: "AP Diff", dataKey: "apDiff", toggleable: true },

  // Additional LIFT-ACCOUNTS columns
  { header: "Date", dataKey: "timestamp", toggleable: true },
  { header: "Firm Name", dataKey: "firmName", toggleable: true },
  { header: "Party Name", dataKey: "vendorName", toggleable: true },
  { header: "Product Name", dataKey: "rawMaterialName", toggleable: true },
  { header: "Qty", dataKey: "quantity", toggleable: true },
  { header: "Area Lifting", dataKey: "areaLifting", toggleable: true },
  { header: "Truck No.", dataKey: "truckNo", toggleable: true },
  { header: "Transporter", dataKey: "transporterName", toggleable: true },
  { header: "Bill No.", dataKey: "billNo", toggleable: true },
  { header: "Type", dataKey: "liftType", toggleable: true },
  { header: "Bilty No.", dataKey: "biltyNo", toggleable: true },
  { header: "Type Of Rate", dataKey: "typeOfTransportingRate", toggleable: true },
  { header: "Rate", dataKey: "materialRate", toggleable: true },
  { header: "Truck Qty", dataKey: "truckQty", toggleable: true },
  { header: "Bill Image", dataKey: "billImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Bilty Image", dataKey: "biltyImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Weight Slip", dataKey: "weightSlipImageUrl", toggleable: true, isLink: true, linkText: "View" },
  { header: "Qty Diff Status", dataKey: "qtyDifferenceStatus", toggleable: true },
  { header: "Diff Qty", dataKey: "differenceQty", toggleable: true },
  { header: "Total Freight", dataKey: "totalFreight", toggleable: true },
  { header: "Status", dataKey: "status", toggleable: true },

  // INDENT-PO columns
  { header: "PO Timestamp", dataKey: "poTimestamp", toggleable: true },
  { header: "Generated By", dataKey: "poGeneratedBy", toggleable: true },
  { header: "Vendor (PO)", dataKey: "poVendor", toggleable: true },
  { header: "Quantity (PO)", dataKey: "poQuantity", toggleable: true },
  { header: "Current Stock", dataKey: "poCurrentStock", toggleable: true },
  { header: "Priority", dataKey: "poPriority", toggleable: true },
  { header: "Delivery Order No.", dataKey: "poDeliveryOrderNo", toggleable: true },
  { header: "Notes (PO)", dataKey: "poNotes", toggleable: true },
  { header: "Approved Qty", dataKey: "poApprovedQty", toggleable: true },
  { header: "Approval Status", dataKey: "poApprovalStatus", toggleable: true },
  { header: "Rate (PO)", dataKey: "poRate", toggleable: true },
  { header: "Lead Time (days)", dataKey: "poLeadTime", toggleable: true },
  { header: "Total Quantity (PO)", dataKey: "poTotalQuantity", toggleable: true },
  { header: "Total Amount", dataKey: "poTotalAmount", toggleable: true },
  { header: "Alumina % (PO)", dataKey: "poAluminaPercent", toggleable: true },
  { header: "Iron % (PO)", dataKey: "poIronPercent", toggleable: true },
  { header: "Total Lifted (PO)", dataKey: "poTotalLifted", toggleable: true },
  { header: "Pending Qty (PO)", dataKey: "poPendingQty", toggleable: true },
  { header: "Status (PO)", dataKey: "poStatus", toggleable: true },

  // TL columns
  { header: "TL Raw Material", dataKey: "tlRawMaterial", toggleable: true },

  { header: "Actions", dataKey: "actions", toggleable: false, alwaysVisible: true },
];

const HISTORY_COLUMNS_META = [
  { header: "Date", dataKey: "Timestamp", toggleable: true, alwaysVisible: true },
  { header: "Lift ID", dataKey: "Lift ID", toggleable: true, alwaysVisible: true },
  { header: "Indent Number", dataKey: "Indent Number", toggleable: true, alwaysVisible: true },
  { header: "Firm Name", dataKey: "Firm Name", toggleable: true },
  { header: "Party Name", dataKey: "Party Name", toggleable: true },
  { header: "Product Name", dataKey: "Product Name", toggleable: true },
  { header: "Transporter", dataKey: "Transporter Name", toggleable: true },
  { header: "Status", dataKey: "Status", toggleable: true },
  { header: "Remarks", dataKey: "Remarks", toggleable: true },
  { header: "Lift Number", dataKey: "Lift Number", toggleable: true },
  { header: "Type", dataKey: "Type", toggleable: true },
  { header: "Bill No.", dataKey: "Bill No.", toggleable: true },
  { header: "Qty", dataKey: "Qty", toggleable: true },
  { header: "Area Lifting", dataKey: "Area Lifting", toggleable: true },
  { header: "Truck No.", dataKey: "Truck No.", toggleable: true },
  { header: "Bill Image", dataKey: "Bill Image", toggleable: true, isLink: true, linkText: "View" },
  { header: "Bilty No.", dataKey: "Bilty No.", toggleable: true },
  { header: "Type Of Rate", dataKey: "Type Of Rate", toggleable: true },
  { header: "Rate", dataKey: "Rate", toggleable: true },
  { header: "Truck Qty", dataKey: "Truck Qty", toggleable: true },
  { header: "Bilty Image", dataKey: "Bilty Image", toggleable: true, isLink: true, linkText: "View" },
  { header: "Qty Diff Status", dataKey: "Qty Diff Status", toggleable: true },
  { header: "Diff Qty", dataKey: "Diff Qty", toggleable: true },
  { header: "Weight Slip", dataKey: "Weight Slip", toggleable: true, isLink: true, linkText: "View" },
  { header: "Total Freight", dataKey: "Total Freight", toggleable: true },
  { header: "Actions", dataKey: "actions", toggleable: false, alwaysVisible: true },
];


export default function MismatchAnalysis() {
  const { user } = useContext(AuthContext);
  const [liftAccountsData, setLiftAccountsData] = useState([]);
  const [purchaseOrdersData, setPurchaseOrdersData] = useState([]);
  const [tlData, setTlData] = useState([]);
  const [loadingLifts, setLoadingLifts] = useState(true);
  const [loadingPOs, setLoadingPOs] = useState(true);
  const [loadingTL, setLoadingTL] = useState(true);
  const [loadingMismatch, setLoadingMismatch] = useState(true);
  const [error, setError] = useState(null);
  const [activeTab, setActiveTab] = useState("rateMismatch");
  const [editingRow, setEditingRow] = useState(null);
  const [editingRowData, setEditingRowData] = useState(null); // Store full row data
  const [submitting, setSubmitting] = useState(false);
  const [visibleRateMismatchColumns, setVisibleRateMismatchColumns] = useState({});
  const [visibleQuantityMismatchColumns, setVisibleQuantityMismatchColumns] = useState({});
  const [visibleMaterialMismatchColumns, setVisibleMaterialMismatchColumns] = useState({});
  const [visibleHistoryColumns, setVisibleHistoryColumns] = useState({});
  const [mismatchSheetData, setMismatchSheetData] = useState([]);
  const [formData, setFormData] = useState({});
  const [submittedRows, setSubmittedRows] = useState(new Set());

  const [filters, setFilters] = useState({
    vendorName: "all",
    materialName: "all",
    firmName: "all",
    orderNumber: "all",
  });

  // Fetch Mismatch data from Supabase
  const fetchMismatchSheetData = useCallback(async () => {
    setLoadingMismatch(true);
    try {
      const { data, error: fetchError } = await supabase
        .from("Mismatch")
        .select("*")
        .order("Timestamp", { ascending: false });

      if (fetchError) throw fetchError;

      setMismatchSheetData(data || []);
    } catch (error) {
      console.error("Failed to load Mismatch data:", error);
      setMismatchSheetData([]);
    } finally {
      setLoadingMismatch(false);
    }
  }, []);

  // Initialize column visibility
  useEffect(() => {
    const initializeVisibility = (columnsMeta) => {
      const visibility = {};
      columnsMeta.forEach((col) => {
        visibility[col.dataKey] = col.alwaysVisible || col.toggleable;
      });
      return visibility;
    };
    setVisibleRateMismatchColumns(initializeVisibility(RATE_MISMATCH_COLUMNS_META));
    setVisibleQuantityMismatchColumns(initializeVisibility(QUANTITY_MISMATCH_COLUMNS_META));
    setVisibleMaterialMismatchColumns(initializeVisibility(MATERIAL_MISMATCH_COLUMNS_META));
    setVisibleHistoryColumns(initializeVisibility(HISTORY_COLUMNS_META));
  }, []);

  // Initialize form data
  const initializeFormData = (rowId) => {
    setFormData({
      status: 'Credit Notes',
      remarks: ''
    });
  };

  // Handle form changes
  const handleFormChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  // Action handlers
  const handleViewDetails = (item, mismatchType) => {
    const details = {
      rateMismatch: {
        title: "Rate Mismatch Details",
        content: `Lift ID: ${item.id}\nMaterial Rate: ₹${item.materialRate}\nPO Rate: ₹${item.poRate}\nDifference: ₹${item.rateDifference}\nVendor: ${item.vendorName}\nMaterial: ${item.material}`
      },
      quantityMismatch: {
        title: "Quantity Mismatch Details",
        content: `Lift No: ${item.liftNo}\nLifting Qty (Col J): ${item.liftedQty}\nActual Qty (Col Y): ${item.actualQuantityY}\nDifference: ${item.qtyDifference}\nVendor: ${item.vendorName}\nMaterial: ${item.rawMaterialName}`
      },
      materialMismatch: {
        title: "Material Properties Mismatch Details",
        content: `Lift No: ${item.liftNo}\nRaw Material: ${item.rawMaterial}\nAlumina: TL ${item.tlAlumina}% vs Lift ${item.liftAlumina}% (Diff: ${item.aluminaDiff}%)\nIron: TL ${item.tlIron}% vs Lift ${item.liftIron}% (Diff: ${item.ironDiff}%)\nAP: TL ${item.tlAP} vs Lift ${item.liftAP} (Diff: ${item.apDiff})`
      }
    };

    toast.info(details[mismatchType].title, {
      description: details[mismatchType].content,
      duration: 10000,
    });
  };

  const handleCorrectData = (item, mismatchType) => {
    setEditingRow(item.id || item.liftNo);
    setEditingRowData(item); // Store the full item data
    initializeFormData(item.id || item.liftNo);
  };

  const handleReportIssue = (item, mismatchType) => {
    toast.success("Issue Reported", {
      description: `Mismatch issue has been reported to the quality team. Reference: ${item.id || item.liftNo}`,
      duration: 3000,
    });
  };

  const handleExportData = (item, mismatchType) => {
    // Create CSV data for the specific item
    const csvData = Object.entries(item)
      .filter(([key]) => !key.startsWith('_'))
      .map(([key, value]) => `"${key}","${value}"`)
      .join('\n');

    const blob = new Blob([`"Field","Value"\n${csvData}`], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${mismatchType}_${item.id || item.liftNo}_${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);

    toast.success("Data Exported", {
      description: `${mismatchType} data exported successfully for ${item.id || item.liftNo}`,
      duration: 3000,
    });
  };

  // Submit form data to Supabase Mismatch table
  const submitFormData = async () => {
    if (!editingRow || !editingRowData) return;

    const data = formData;

    if (!data) {
      toast.error('No form data to submit');
      return;
    }

    setSubmitting(true);

    try {
      const currentDate = new Date();

      // Prepare data for Mismatch table according to schema
      const mismatchData = {
        "Timestamp": currentDate.toLocaleString("en-GB", { hour12: false }).replace(",", ""),
        "Lift ID": editingRowData.id || editingRowData.liftNo || "",
        "Indent Number": editingRowData.indentNo || "",
        "Firm Name": editingRowData.firmName || "",
        "Party Name": editingRowData.vendorName || "",
        "Product Name": editingRowData.material || editingRowData.rawMaterialName || "",
        "Transporter Name": editingRowData.transporterName || "",
        "Status": data.status || 'Credit Notes',
        "Remarks": data.remarks || '',
        "Planned": null,
        "Actual": null,
        "Planned2": null,
        "Actual2": null,
        "Planned3": null,
        "Actual3": null,
        "Planned4": null,
        "Actual4": null,
        "Planned5": null,
        "Actual5": null,
        "Planned6": null,
        "Actual6": null,
        "Remark": data.remarks || '',
        "Lift Number": editingRowData.liftNo || "",
        "Type": editingRowData.liftType || "",
        "Bill No.": editingRowData.billNo || "",
        "Qty": Number(editingRowData.quantity) || 0,
        "Area Lifting": editingRowData.areaLifting || "",
        "Truck No.": editingRowData.truckNo || "",
        "Transporter": editingRowData.transporterName || "",
        "Bill Image": editingRowData.billImageUrl || "",
        "Bilty No.": editingRowData.biltyNo || "",
        "Type Of Rate": editingRowData.typeOfTransportingRate || "",
        "Rate": Number(editingRowData.materialRate) || 0,
        "Truck Qty": Number(editingRowData.truckQty) || 0,
        "Bilty Image": editingRowData.biltyImageUrl || "",
        "Qty Diff Status": editingRowData.qtyDifferenceStatus || "",
        "Diff Qty": Number(editingRowData.differenceQty) || 0,
        "Weight Slip": editingRowData.weightSlipImageUrl || "",
        "Total Freight": Number(editingRowData.totalFreight) || 0
      };

      // Insert into Supabase Mismatch table
      const { data: insertedData, error: insertError } = await supabase
        .from("Mismatch")
        .insert([mismatchData])
        .select();

      if (insertError) throw insertError;

      // Mark as submitted
      setSubmittedRows(prev => new Set([...prev, `mismatch_${editingRow}`]));
      setEditingRow(null);
      setEditingRowData(null);

      const actualDateTime = currentDate.toLocaleString("en-GB", { hour12: false }).replace(",", "");
      toast.success(`✅ SUCCESS: Mismatch data submitted to Mismatch table for: ${editingRow}\nSubmitted at: ${actualDateTime}`);

      // Refresh data
      setTimeout(() => {
        fetchLiftAccountsData();
        fetchPurchaseOrdersData();
        fetchTLData();
        fetchMismatchSheetData();
      }, 1000);

    } catch (error) {
      console.error('Submission error:', error);
      toast.error(`❌ SUBMISSION FAILED: ${error.message}`);
    } finally {
      setSubmitting(false);
    }
  };

  // Modal render function
  const renderModal = () => {
    if (!editingRow) return null;

    return (
      <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50">

        <div className="bg-white rounded-xl shadow-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-gray-900">Submit Mismatch Correction</h3>
              <button
                onClick={() => setEditingRow(null)}
                className="text-gray-400 hover:text-gray-600"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="mb-6 p-4 bg-gray-50 rounded-lg">
              <h4 className="font-medium text-gray-700 mb-2">Mismatch Details</h4>
              <div className="grid grid-cols-1 gap-2 text-sm">
                <div><span className="text-gray-600">Lift ID:</span> {editingRow}</div>
                <div><span className="text-gray-600">Mismatch Type:</span> {activeTab}</div>
                <div className="text-xs text-gray-500 mt-2">
                  This will submit the complete lift data along with your status and remarks to the Mismatch sheet.
                </div>
              </div>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Debite Note</label>
                <select
                  value={formData.status || 'Credit Notes'}
                  onChange={(e) => handleFormChange('status', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white text-sm"
                >
                  <option value="Credit Notes">Yes</option>
                  <option value="Others">No</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Reason</label>
                <textarea
                  value={formData.remarks || ''}
                  onChange={(e) => handleFormChange('remarks', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-sm resize-none"
                  placeholder="Enter correction details and notes..."
                  rows={4}
                />
              </div>
            </div>

            <div className="flex justify-end space-x-3 pt-6 mt-6 border-t border-gray-200">
              <button
                onClick={() => setEditingRow(null)}
                disabled={submitting}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-500 disabled:opacity-50 transition-colors duration-200"
              >
                Cancel
              </button>
              <button
                onClick={submitFormData}
                disabled={submitting}
                className="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-sm hover:shadow-md"
              >
                {submitting ? (
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <Save className="w-4 h-4 mr-2" />
                )}
                {submitting ? 'Submitting...' : 'Submit to Mismatch Sheet'}
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  };

  // Fetch LIFT-ACCOUNTS data from Supabase
  const fetchLiftAccountsData = useCallback(async () => {
    setLoadingLifts(true);
    setError(null);
    try {
      const { data, error: fetchError } = await supabase
        .from("LIFT-ACCOUNTS")
        .select("*")
        .order("Timestamp", { ascending: false });

      if (fetchError) throw fetchError;

      let formattedData = (data || [])
        .filter((row) => row["Planned 4"] && row["Actual 4"])
        .map((row) => {

          // Format timestamp for display
          let createdAt = "";
          let timestamp = "";
          if (row["Timestamp"]) {
            try {
              const d = new Date(row["Timestamp"]);
              if (!isNaN(d.getTime())) {
                createdAt = d
                  .toLocaleString("en-GB", {
                    day: "2-digit",
                    month: "2-digit",
                    year: "numeric",
                    hour: "2-digit",
                    minute: "2-digit",
                    second: "2-digit",
                    hour12: false,
                  })
                  .replace(",", "");
                timestamp = createdAt;
              }
            } catch (e) {
              createdAt = String(row["Timestamp"] || "");
              timestamp = createdAt;
            }
          }

          // Format dates
          const formatDate = (dateValue) => {
            if (!dateValue) return "";
            try {
              const d = new Date(dateValue);
              if (!isNaN(d.getTime())) {
                return d.toLocaleDateString("en-GB");
              }
            } catch (e) {
              return String(dateValue);
            }
            return String(dateValue);
          };

          return {
            // Core fields
            id: String(row["Lift No"] || "").trim(),
            liftNo: String(row["Lift No"] || "").trim(),
            indentNo: String(row["Indent no."] || "").trim(),
            vendorName: String(row["Vendor Name"] || "").trim(),
            quantity: String(row["Qty"] || "").trim(),
            material: String(row["Raw Material Name"] || "").trim(),
            rawMaterialName: String(row["Raw Material Name"] || "").trim(),

            // LIFT-ACCOUNTS columns
            billNo: String(row["Bill No."] || "").trim(),
            areaLifting: String(row["Area lifting"] || "").trim(),
            leadTimeToFactory: String(row["Lead Time To Reach Factory (days)"] || "").trim(),
            liftingQty: String(row["Lifting Qty"] || "").trim(),
            liftType: String(row["Type"] || "").trim(),
            transporterName: String(row["Transporter Name"] || "").trim(),
            truckNo: String(row["Truck No."] || "").trim(),
            driverNo: String(row["Driver No."] || "").trim(),
            biltyNo: String(row["Bilty No."] || "").trim(),
            typeOfTransportingRate: String(row["Type Of Transporting Rate"] || "").trim(),
            materialRate: String(row["Rate"] || "").trim(),
            billImageUrl: String(row["Bill Image"] || "").trim(),
            truckQty: String(row["Truck Qty"] || "").trim(),
            dateOfReceiving: formatDate(row["Date Of Receiving"]),
            totalBillQuantity: String(row["Total Bill Quantity"] || "").trim(),
            actualQuantity: String(row["Actual Quantity"] || "").trim(),
            actualQuantityY: String(row["Actual Quantity"] || "").trim(),
            physicalCondition: String(row["Physical Condition"] || "").trim(),
            moisture: String(row["Moisture"] || "").trim(),
            physicalImageUrl: String(row["Physical Image Of Product"] || "").trim(),
            weightSlipImageUrl: String(row["Image Of Weight Slip"] || "").trim(),
            biltyNo2: String(row["Bilty No. 2"] || "").trim(),
            biltyImageUrl: String(row["Bilty Image"] || "").trim(),
            status: String(row["Status"] || "").trim(),
            dateOfTest: formatDate(row["Date Of Test"]),
            moisturePercent: String(row["Moisture Percent Age %"] || "").trim(),
            bdPercent: String(row["BD Percent Age %"] || "").trim(),
            apPercent: String(row["AP Percent Age %"] || "").trim(),
            aluminaPercent: String(row["Alumina Percent Age %"] || "").trim(),
            ironPercent: String(row["Iron Percent Age %"] || "").trim(),
            sieveAnalysis: String(row["Sieve Analysis"] || "").trim(),
            loiPercent: String(row["LOI %"] || "").trim(),
            sio2Percent: String(row["SIO2 %"] || "").trim(),
            caoPercent: String(row["CaO %"] || "").trim(),
            mgoPercent: String(row["MgO %"] || "").trim(),
            tio2Percent: String(row["TiO2 %"] || "").trim(),
            k2oNa2oPercent: String(row["K2O + Na2O %"] || "").trim(),
            freeIronPercent: String(row["Free Iron %"] || "").trim(),
            firmName: String(row["Firm Name"] || "").trim(),
            weightSlipQty: String(row["Weight Slip Qty"] || "").trim(),
            transporterRate: String(row["Transporter Rate"] || "").trim(),
            qtyDifferenceStatus: String(row["Qty Difference Status"] || "").trim(),
            differenceQty: String(row["Difference Qty"] || "").trim(),
            totalFreight: String(row["Total Freight"] || "").trim(),

            // Additional fields for existing functionality
            createdAt: createdAt,
            liftedQty: String(row["Lifting Qty"] || "").trim(),
            dateOfReceiving_formatted: formatDate(row["Date Of Receiving"]),
            physicalCondition_fromSheet: String(row["Physical Condition"] || "").trim(),
            liftAlumina: String(row["Alumina Percent Age %"] || "").trim(),
            liftIron: String(row["Iron Percent Age %"] || "").trim(),
            liftAP: String(row["AP Percent Age %"] || "").trim(),
            timestamp: timestamp,
          };
        });

      // Filter by user's firm name if applicable
      if (user?.firmName && user.firmName.toLowerCase() !== "all") {
        const userFirmNameLower = user.firmName.toLowerCase();
        formattedData = formattedData.filter(
          (lift) => lift.firmName && String(lift.firmName).toLowerCase() === userFirmNameLower,
        );
      }

      setLiftAccountsData(formattedData);
    } catch (err) {
      setError(`Failed to load LIFT-ACCOUNTS data: ${err.message}`);
      setLiftAccountsData([]);
    } finally {
      setLoadingLifts(false);
    }
  }, [user]);

  // Fetch INDENT-PO data from Supabase
  const fetchPurchaseOrdersData = useCallback(async () => {
    setLoadingPOs(true);
    try {
      const { data, error: fetchError } = await supabase
        .from("INDENT-PO")
        .select("*");

      if (fetchError) throw fetchError;

      // Format dates
      const formatDate = (dateValue) => {
        if (!dateValue) return "";
        try {
          const d = new Date(dateValue);
          if (!isNaN(d.getTime())) {
            return d.toLocaleDateString("en-GB");
          }
        } catch (e) {
          return String(dateValue);
        }
        return String(dateValue);
      };

      const formattedData = (data || []).map((row) => {
        // Format timestamp for display
        let poTimestamp = "";
        if (row["Timestamp"]) {
          try {
            const d = new Date(row["Timestamp"]);
            if (!isNaN(d.getTime())) {
              poTimestamp = d
                .toLocaleString("en-GB", {
                  day: "2-digit",
                  month: "2-digit",
                  year: "numeric",
                  hour: "2-digit",
                  minute: "2-digit",
                  second: "2-digit",
                  hour12: false,
                })
                .replace(",", "");
            }
          } catch (e) {
            poTimestamp = String(row["Timestamp"] || "");
          }
        }

        return {
          // INDENT-PO columns
          poTimestamp: poTimestamp,
          indentId: String(row["Indent Id."] || "").trim(),
          poFirmName: String(row["Firm Name"] || "").trim(),
          poGeneratedBy: String(row["Generated By"] || "").trim(),
          poVendor: String(row["Vendor"] || "").trim(),
          poMaterial: String(row["Material"] || "").trim(),
          poQuantity: String(row["Quantity"] || "").trim(),
          poCurrentStock: String(row["Current Stock As Per factory"] || "").trim(),
          poPriority: String(row["Priority"] || "").trim(),
          poDeliveryOrderNo: String(row["Delivery Order No."] || "").trim(),
          poNotes: String(row["Notes"] || "").trim(),
          poApprovedQty: String(row["Approved Qty"] || "").trim(),
          poApprovalStatus: String(row["Approval Status"] || "").trim(),
          poRemarks: String(row["Remarks"] || "").trim(),
          poHaveToMake: String(row["Have To Make PO"] || "").trim(),
          poRate: String(row["Rate"] || "").trim(),
          poLeadTime: String(row["Lead Time To Lift (days)"] || "").trim(),
          poTotalQuantity: String(row["Total Quantity"] || "").trim(),
          poTotalAmount: String(row["Total Amount"] || "").trim(),
          poCopyUrl: String(row["PO Copy"] || "").trim(),
          poAdvanceToBePaid: String(row["Advance To Be Paid"] || "").trim(),
          poToBePaidAmount: String(row["To Be Paid Amount"] || "").trim(),
          poWhenToBePaid: formatDate(row["When To Be Paid Amount"]),
          poPONotes: String(row["PO Notes"] || "").trim(),
          poAluminaPercent: String(row["Alumina %"] || "").trim(),
          poIronPercent: String(row["Iron %"] || "").trim(),
          poTotalLifted: String(row["Total Lifted"] || "").trim(),
          poPendingQty: String(row["Pending Qty"] || "").trim(),
          poOrderCancelQty: String(row["Order Cancel Qty"] || "").trim(),
          poStatus: String(row["Status"] || "").trim(),

          // Additional fields for existing functionality
          indentNo: String(row["Indent Id."] || "").trim(),
          firmName: String(row["Firm Name"] || "").trim(),
          vendorName: String(row["Vendor name"] || row["Vendor"] || "").trim(),
          rawMaterialName: String(row["Material"] || "").trim(),
        };
      });

      setPurchaseOrdersData(formattedData);
    } catch (error) {
      setError(prev => prev ? `${prev}\nFailed to load PO data: ${error.message}` : `Failed to load PO data: ${error.message}`);
      setPurchaseOrdersData([]);
    } finally {
      setLoadingPOs(false);
    }
  }, []);

  const fetchTLData = useCallback(async () => {
    setLoadingTL(true);
    try {
      const { data, error: fetchError } = await supabase
        .from("TL")
        .select("*");

      if (fetchError) throw fetchError;

      const formattedData = (data || [])
        .map((row, index) => ({
          _id: `tl-${index}`,
          rawMaterial: String(row["Raw Material"] || "").trim(),
          alumina: String(row["Alumina"] || "").trim(),
          iron: String(row["Iron"] || "").trim(),
          ap: String(row["AP"] || "").trim(),
        }))
        .filter(item => item.rawMaterial && item.rawMaterial.trim() !== "");

      setTlData(formattedData);
    } catch (err) {
      setError(prev => prev ? `${prev}\nFailed to load TL data: ${err.message}` : `Failed to load TL data: ${err.message}`);
      setTlData([]);
    } finally {
      setLoadingTL(false);
    }
  }, []);

  useEffect(() => {
    fetchLiftAccountsData();
    fetchPurchaseOrdersData();
    fetchTLData();
    fetchMismatchSheetData(); // Add this line

  }, [fetchLiftAccountsData, fetchPurchaseOrdersData, fetchTLData, fetchMismatchSheetData]);

  // Calculate mismatch data (keeping existing calculations unchanged)
  // Helper function to check if an indent number exists in Mismatch sheet
  const isIndentSubmitted = (indentNo) => {
    return mismatchSheetData.some(mismatchRow =>
      mismatchRow.indentNo &&
      indentNo &&
      String(mismatchRow.indentNo).trim() === String(indentNo).trim()
    );
  };

  const rateMismatchData = useMemo(() => {
    return liftAccountsData
      .filter(lift => !isIndentSubmitted(lift.indentNo)) // Filter out submitted rows
      .map((lift) => {
        const liftMaterialRate = parseFloat(lift.materialRate) || 0;
        const correspondingPO = purchaseOrdersData.find(po => po.indentNo === lift.indentNo);
        const poRate = parseFloat(correspondingPO?.poRate) || 0;

        if (Math.abs(liftMaterialRate - poRate) >= 0.01 && liftMaterialRate > 0 && poRate > 0) {
          return {
            ...lift,
            ...(correspondingPO || {}),
            poRate: poRate.toFixed(2),
            rateDifference: (liftMaterialRate - poRate).toFixed(2),
          };
        }
        return null;
      })
      .filter(Boolean);
  }, [liftAccountsData, purchaseOrdersData, mismatchSheetData]);

  const quantityMismatchData = useMemo(() => {
    return liftAccountsData
      .filter(lift => !isIndentSubmitted(lift.indentNo)) // Filter out submitted rows
      .map((lift) => {
        const liftedQty = parseFloat(lift.liftedQty) || 0;
        const actualQuantityY = parseFloat(lift.actualQuantityY) || 0;

        const correspondingPO = purchaseOrdersData.find(po => po.indentNo === lift.indentNo);

        const rowData = {
          ...lift,
          ...(correspondingPO || {}),
        };

        if (Math.abs(liftedQty - actualQuantityY) >= 0.01 && liftedQty > 0 && actualQuantityY > 0) {
          return {
            ...rowData,
            qtyDifference: (liftedQty - actualQuantityY).toFixed(2),
          };
        }
        return null;
      })
      .filter(Boolean);
  }, [liftAccountsData, purchaseOrdersData, mismatchSheetData]);

  const materialMismatchData = useMemo(() => {
    return liftAccountsData
      .filter(lift => !isIndentSubmitted(lift.indentNo)) // Filter out submitted rows
      .map((lift) => {
        const correspondingTL = tlData.find(tl =>
          tl.rawMaterial && lift.material &&
          tl.rawMaterial.toLowerCase().trim() === lift.material.toLowerCase().trim()
        );

        if (!correspondingTL) return null;

        const tlAlumina = parseFloat(correspondingTL.alumina) || 0;
        const liftAlumina = parseFloat(lift.liftAlumina) || 0;
        const tlIron = parseFloat(correspondingTL.iron) || 0;
        const liftIron = parseFloat(lift.liftIron) || 0;
        const tlAP = parseFloat(correspondingTL.ap) || 0;
        const liftAP = parseFloat(lift.liftAP) || 0;

        const aluminaMismatch = Math.abs(tlAlumina - liftAlumina) >= 0.01;
        const ironMismatch = Math.abs(tlIron - liftIron) >= 0.01;
        const apMismatch = Math.abs(tlAP - liftAP) >= 0.01;

        if ((aluminaMismatch || ironMismatch || apMismatch) &&
          (tlAlumina > 0 || liftAlumina > 0 || tlIron > 0 || liftIron > 0 || tlAP > 0 || liftAP > 0)) {
          const correspondingPO = purchaseOrdersData.find(po => po.indentNo === lift.indentNo);
          return {
            ...lift,
            ...(correspondingPO || {}),
            rawMaterial: lift.material,
            tlRawMaterial: correspondingTL.rawMaterial,
            tlAlumina: tlAlumina.toFixed(2),
            tlIron: tlIron.toFixed(2),
            tlAP: tlAP.toFixed(2),
            aluminaDiff: (liftAlumina - tlAlumina).toFixed(2),
            ironDiff: (liftIron - tlIron).toFixed(2),
            apDiff: (liftAP - tlAP).toFixed(2),
          };
        }
        return null;
      })
      .filter(Boolean);
  }, [liftAccountsData, tlData, purchaseOrdersData, mismatchSheetData]);
  // Filter options (keeping existing logic unchanged)
  const uniqueFilterOptions = useMemo(() => {
    const vendors = new Set();
    const materials = new Set();
    const firms = new Set();
    const orders = new Set();

    [...rateMismatchData, ...quantityMismatchData, ...materialMismatchData].forEach((item) => {
      if (item.vendorName) vendors.add(item.vendorName);
      if (item.material || item.rawMaterialName || item.rawMaterial) {
        materials.add(item.material || item.rawMaterialName || item.rawMaterial);
      }
      if (item.firmName) firms.add(item.firmName);
      if (item.indentNo) orders.add(item.indentNo);
    });

    return {
      vendorName: [...vendors].sort(),
      materialName: [...materials].sort(),
      firmName: [...firms].sort(),
      orderNumber: [...orders].sort(),
    };
  }, [rateMismatchData, quantityMismatchData, materialMismatchData]);

  // Apply filters (keeping existing logic unchanged)
  const filteredRateMismatchData = useMemo(() => {
    let filtered = rateMismatchData.filter(item => !submittedRows.has(`mismatch_${item.id}`));
    if (filters.vendorName !== "all") {
      filtered = filtered.filter((item) => item.vendorName === filters.vendorName);
    }
    if (filters.materialName !== "all") {
      filtered = filtered.filter((item) => item.material === filters.materialName);
    }
    if (filters.firmName !== "all") {
      filtered = filtered.filter((item) => item.firmName === filters.firmName);
    }
    if (filters.orderNumber !== "all") {
      filtered = filtered.filter((item) => item.indentNo === filters.orderNumber);
    }
    return filtered;
  }, [rateMismatchData, filters, submittedRows]);

  const filteredQuantityMismatchData = useMemo(() => {
    let filtered = quantityMismatchData.filter(item => !submittedRows.has(`mismatch_${item.liftNo}`));
    if (filters.vendorName !== "all") {
      filtered = filtered.filter((item) => item.vendorName === filters.vendorName);
    }
    if (filters.materialName !== "all") {
      filtered = filtered.filter((item) => item.rawMaterialName === filters.materialName);
    }
    if (filters.firmName !== "all") {
      filtered = filtered.filter((item) => item.firmName === filters.firmName);
    }
    if (filters.orderNumber !== "all") {
      filtered = filtered.filter((item) => item.indentNo === filters.orderNumber);
    }
    return filtered;
  }, [quantityMismatchData, filters, submittedRows]);

  const filteredMaterialMismatchData = useMemo(() => {
    let filtered = materialMismatchData.filter(item => !submittedRows.has(`mismatch_${item.liftNo}`));
    if (filters.vendorName !== "all") {
      filtered = filtered.filter((item) => item.vendorName === filters.vendorName);
    }
    if (filters.materialName !== "all") {
      filtered = filtered.filter((item) => item.rawMaterial === filters.materialName);
    }
    if (filters.firmName !== "all") {
      filtered = filtered.filter((item) => item.firmName === filters.firmName);
    }
    if (filters.orderNumber !== "all") {
      filtered = filtered.filter((item) => item.indentNo === filters.orderNumber);
    }
    return filtered;
  }, [materialMismatchData, filters, submittedRows]);

  // Event handlers (keeping existing logic unchanged)
  const handleFilterChange = (key, value) => {
    setFilters((prev) => ({ ...prev, [key]: value }));
  };

  const clearAllFilters = () => {
    setFilters({
      vendorName: "all",
      materialName: "all",
      firmName: "all",
      orderNumber: "all",
    });
  };

  const handleToggleColumn = (tab, dataKey, checked) => {
    if (tab === "rate") {
      setVisibleRateMismatchColumns((prev) => ({ ...prev, [dataKey]: checked }));
    } else if (tab === "quantity") {
      setVisibleQuantityMismatchColumns((prev) => ({ ...prev, [dataKey]: checked }));
    } else if (tab === "material") {
      setVisibleMaterialMismatchColumns((prev) => ({ ...prev, [dataKey]: checked }));
    } else if (tab === "history") {
      setVisibleHistoryColumns((prev) => ({ ...prev, [dataKey]: checked }));
    }
  };

  const handleSelectAllColumns = (tab, columnsMeta, selectAll) => {
    const newVisibility = {};
    columnsMeta.forEach((col) => {
      newVisibility[col.dataKey] = col.alwaysVisible || selectAll;
    });
    if (tab === "rate") {
      setVisibleRateMismatchColumns(newVisibility);
    } else if (tab === "quantity") {
      setVisibleQuantityMismatchColumns(newVisibility);
    } else if (tab === "material") {
      setVisibleMaterialMismatchColumns(newVisibility);
    } else if (tab === "history") {
      setVisibleHistoryColumns(newVisibility);
    }
  };

  // Render cell with action buttons
  const renderCell = (item, column) => {
    const value = item[column.dataKey];

    if (column.dataKey === "actions") {
      let mismatchType = "rateMismatch";
      if (activeTab === "quantityMismatch") mismatchType = "quantityMismatch";
      if (activeTab === "materialMismatch") mismatchType = "materialMismatch";

      if (activeTab === "history") {
        return <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">Submitted</Badge>;
      }

      return (
        <div className="flex gap-2 whitespace-nowrap">
          <button
            onClick={() => handleCorrectData(item, mismatchType)}
            className="inline-flex items-center px-3 py-1 text-xs font-medium text-white bg-gradient-to-r from-blue-500 to-blue-600 rounded-md hover:from-blue-600 hover:to-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all duration-200 shadow-sm hover:shadow-md"
          >
            <Edit className="w-3 h-3 mr-1" />
            Correct Data
          </button>
        </div>
      );
    }

    if (column.isLink) {
      return value ? (
        <a
          href={String(value).startsWith("http") ? value : `https://${value}`}
          target="_blank"
          rel="noopener noreferrer"
          className="text-purple-600 hover:text-purple-800 hover:underline inline-flex items-center text-xs"
        >
          <ExternalLink className="h-3 w-3 mr-1" /> {column.linkText || "View"}
        </a>
      ) : (
        <span className="text-gray-400 text-xs">N/A</span>
      );
    }

    // Highlight differences with color coding
    if (column.dataKey === "rateDifference" || column.dataKey === "qtyDifference" ||
      column.dataKey === "aluminaDiff" || column.dataKey === "ironDiff" || column.dataKey === "apDiff") {
      const numValue = parseFloat(value) || 0;
      return (
        <span className={numValue < 0 ? "text-red-600 font-semibold" : "text-green-600 font-semibold"}>
          {numValue > 0 ? `+${value}` : value}
        </span>
      );
    }

    return value || <span className="text-gray-400 text-xs">N/A</span>;
  };

  const renderTableSection = (tabKey, title, description, data, columnsMeta, visibilityState) => {
    const visibleCols = columnsMeta.filter((col) => visibilityState[col.dataKey]);
    const isLoading = (tabKey === "rateMismatch" ? loadingLifts || loadingPOs :
      tabKey === "materialMismatch" ? loadingLifts || loadingTL : loadingLifts) && data.length === 0;
    const hasError = error && data.length === 0;

    return (
      <Card className="shadow-sm border border-border flex-1 flex-col">
        <CardHeader className="py-3 px-4 bg-red-50/50">
          <div className="flex justify-between items-center">
            <div>
              <CardTitle className="flex items-center text-md font-semibold text-foreground">
                {tabKey === "rateMismatch" ? (
                  <DollarSign className="h-5 w-5 text-red-600 mr-2" />
                ) : tabKey === "quantityMismatch" ? (
                  <Package className="h-5 w-5 text-red-600 mr-2" />
                ) : (
                  <Beaker className="h-5 w-5 text-red-600 mr-2" />
                )}
                {title} ({data.length})
              </CardTitle>
              <CardDescription className="text-sm text-muted-foreground mt-0.5">{description}</CardDescription>
            </div>
            <div className="flex gap-2">
              <Button
                onClick={() => {
                  fetchLiftAccountsData();
                  fetchPurchaseOrdersData();
                  fetchTLData();
                }}
                variant="outline"
                size="sm"
                className="h-8 text-xs bg-white"
              >
                <RefreshCw className="mr-1.5 h-3.5 w-3.5" />
                Refresh
              </Button>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" size="sm" className="h-8 text-xs bg-white">
                    <MixerHorizontalIcon className="mr-1.5 h-3.5 w-3.5" /> View Columns
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[240px] p-3">
                  <div className="grid gap-2">
                    <p className="text-sm font-medium">Toggle Columns</p>
                    <div className="flex items-center justify-between mt-1 mb-2">
                      <Button
                        variant="link"
                        size="sm"
                        className="p-0 h-auto text-xs"
                        onClick={() => handleSelectAllColumns(
                          tabKey === "rateMismatch" ? "rate" :
                            tabKey === "quantityMismatch" ? "quantity" : "material",
                          columnsMeta, true)}
                      >
                        Select All
                      </Button>
                      <span className="text-gray-300 mx-1">|</span>
                      <Button
                        variant="link"
                        size="sm"
                        className="p-0 h-auto text-xs"
                        onClick={() => handleSelectAllColumns(
                          tabKey === "rateMismatch" ? "rate" :
                            tabKey === "quantityMismatch" ? "quantity" :
                              tabKey === "materialMismatch" ? "material" : "history",
                          columnsMeta, false)}
                      >
                        Deselect All
                      </Button>
                    </div>
                    <div className="space-y-1.5 max-h-48 overflow-y-auto">
                      {columnsMeta
                        .filter((col) => col.toggleable)
                        .map((col) => (
                          <div key={`toggle-${tabKey}-${col.dataKey}`} className="flex items-center space-x-2">
                            <Checkbox
                              id={`toggle-${tabKey}-${col.dataKey}`}
                              checked={!!visibilityState[col.dataKey]}
                              onCheckedChange={(checked) =>
                                handleToggleColumn(
                                  tabKey === "rateMismatch" ? "rate" :
                                    tabKey === "quantityMismatch" ? "quantity" :
                                      tabKey === "materialMismatch" ? "material" : "history",
                                  col.dataKey, Boolean(checked))
                              }
                              disabled={col.alwaysVisible}
                            />
                            <Label htmlFor={`toggle-${tabKey}-${col.dataKey}`} className="text-xs font-normal cursor-pointer">
                              {col.header} {col.alwaysVisible && <span className="text-gray-400 ml-0.5 text-xs">(Fixed)</span>}
                            </Label>
                          </div>
                        ))}
                    </div>
                  </div>
                </PopoverContent>
              </Popover>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0 flex-1 flex-col">
          {isLoading ? (
            <div className="flex flex-col justify-center items-center py-10 flex-1">
              <Loader2 className="h-8 w-8 text-red-600 animate-spin mb-3" />
              <p className="text-muted-foreground ml-2">Loading mismatch data...</p>
            </div>
          ) : hasError ? (
            <div className="flex flex-col items-center justify-center py-10 px-4 border-2 border-dashed border-destructive-foreground bg-destructive/10 rounded-lg mx-4 my-4 text-center flex-1">
              <AlertTriangle className="h-10 w-10 text-destructive mb-3" />
              <p className="font-medium text-destructive">Error Loading Data</p>
              <p className="text-sm text-muted-foreground max-w-md">{error}</p>
            </div>
          ) : data.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-10 px-4 border-2 border-dashed border-green-200/50 bg-green-50/50 rounded-lg mx-4 my-4 text-center flex-1">
              <Info className="h-12 w-12 text-green-500 mb-3" />
              <p className="font-medium text-foreground">No Mismatches Found</p>
              <p className="text-sm text-muted-foreground text-center">
                {tabKey === "rateMismatch"
                  ? "All material rates match their corresponding PO rates."
                  : tabKey === "quantityMismatch"
                    ? "All lifted quantities match their weight slip quantities."
                    : "All material properties match between TL and LIFT-ACCOUNTS sheets."}
                {user?.firmName && user.firmName.toLowerCase() !== "all" && (
                  <span className="block mt-1">(Filtered by firm: {user.firmName})</span>
                )}
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto rounded-b-lg flex-1">
              <Table>
                <TableHeader className="bg-red-50 sticky top-0 z-10">
                  <TableRow>
                    {visibleCols.map((col) => (
                      <TableHead key={col.dataKey} className={`whitespace-nowrap text-xs px-3 py-2 ${col.dataKey === "actions" ? "w-[150px]" : ""}`}>
                        {col.header}
                      </TableHead>
                    ))}
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.map((item, index) => (
                    <TableRow
                      key={`${tabKey}-${item.id || item.liftNo}-${index}`}
                      className="hover:bg-red-50/50 bg-red-100/30 border-l-4 border-l-red-500"
                    >
                      {visibleCols.map((column) => (
                        <TableCell
                          key={`${item.id || item.liftNo}-${column.dataKey}`}
                          className={`text-xs px-3 py-2 ${column.dataKey === "id" || column.dataKey === "liftNo"
                            ? "font-medium text-primary"
                            : column.dataKey === "actions"
                              ? "w-[150px]"
                              : "text-gray-700"
                            }`}
                        >
                          {renderCell(item, column)}
                        </TableCell>
                      ))}
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card >
    );
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-4 sm:p-6">
      {renderModal()}

      <div className="max-w-7xl mx-auto space-y-6">
        <Card className="shadow-md border-none">
          <CardHeader className="p-4 border-b border-gray-200">
            <CardTitle className="flex items-center gap-2 text-gray-700 text-lg">
              <TrendingDown className="h-5 w-5 text-red-600" /> Mismatch Analysis Dashboard
            </CardTitle>
            <CardDescription className="text-gray-500 text-sm">
              Identify and analyze rate, quantity, and material property mismatches across sheets.
              {user?.firmName && user.firmName.toLowerCase() !== "all" && (
                <span className="ml-2 text-red-600 font-medium">• Filtered by: {user.firmName}</span>
              )}
            </CardDescription>
          </CardHeader>
          <CardContent className="p-4">
            <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
              <TabsList className="grid w-full sm:w-[750px] grid-cols-3 mb-4">
                <TabsTrigger value="rateMismatch" className="flex items-center gap-2">
                  <DollarSign className="h-4 w-4" /> Rate Mismatches
                  <Badge variant="destructive" className="ml-1.5 px-1.5 py-0.5 text-xs">
                    {filteredRateMismatchData.length}
                  </Badge>
                </TabsTrigger>
                <TabsTrigger value="quantityMismatch" className="flex items-center gap-2">
                  <Package className="h-4 w-4" /> Quantity Mismatches
                  <Badge variant="destructive" className="ml-1.5 px-1.5 py-0.5 text-xs">
                    {filteredQuantityMismatchData.length}
                  </Badge>
                </TabsTrigger>
                <TabsTrigger value="materialMismatch" className="flex items-center gap-2">
                  <Beaker className="h-4 w-4" /> Material Mismatches
                  <Badge variant="destructive" className="ml-1.5 px-1.5 py-0.5 text-xs">
                    {filteredMaterialMismatchData.length}
                  </Badge>
                </TabsTrigger>
              </TabsList>

              {/* Filters */}
              <div className="mb-4 p-4 bg-red-50/50 rounded-lg">
                <div className="flex items-center gap-2 mb-3">
                  <Filter className="h-4 w-4 text-gray-500" />
                  <Label className="text-sm font-medium">Filters</Label>
                  <Button variant="outline" size="sm" onClick={clearAllFilters} className="ml-auto bg-white">
                    Clear All
                  </Button>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <Select value={filters.vendorName} onValueChange={(value) => handleFilterChange("vendorName", value)}>
                    <SelectTrigger className="h-8 bg-white">
                      <SelectValue placeholder="All Vendors" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Vendors</SelectItem>
                      {uniqueFilterOptions.vendorName.map((vendor) => (
                        <SelectItem key={vendor} value={vendor}>
                          {vendor}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Select value={filters.materialName} onValueChange={(value) => handleFilterChange("materialName", value)}>
                    <SelectTrigger className="h-8 bg-white">
                      <SelectValue placeholder="All Materials" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Materials</SelectItem>
                      {uniqueFilterOptions.materialName.map((material) => (
                        <SelectItem key={material} value={material}>
                          {material}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Select value={filters.firmName} onValueChange={(value) => handleFilterChange("firmName", value)}>
                    <SelectTrigger className="h-8 bg-white">
                      <SelectValue placeholder="All Firms" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Firms</SelectItem>
                      {uniqueFilterOptions.firmName.map((firm) => (
                        <SelectItem key={firm} value={firm}>
                          {firm}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Select value={filters.orderNumber} onValueChange={(value) => handleFilterChange("orderNumber", value)}>
                    <SelectTrigger className="h-8 bg-white">
                      <SelectValue placeholder="All Orders" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Orders</SelectItem>
                      {uniqueFilterOptions.orderNumber.map((order) => (
                        <SelectItem key={order} value={order}>
                          {order}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <TabsContent value="rateMismatch" className="flex-1 flex flex-col mt-0">
                {renderTableSection(
                  "rateMismatch",
                  "Rate Mismatches",
                  "Material rates from LIFT-ACCOUNTS (Column Q) that don't match PO rates from INDENT-PO (Column Y).",
                  filteredRateMismatchData,
                  RATE_MISMATCH_COLUMNS_META,
                  visibleRateMismatchColumns
                )}
              </TabsContent>

              <TabsContent value="quantityMismatch" className="flex-1 flex flex-col mt-0">
                {renderTableSection(
                  "quantityMismatch",
                  "Quantity Mismatches",
                  "Lifting quantities (Column J) that don't match Actual quantities (Column Y) in LIFT-ACCOUNTS.",
                  filteredQuantityMismatchData,
                  QUANTITY_MISMATCH_COLUMNS_META,
                  visibleQuantityMismatchColumns
                )}
              </TabsContent>

              <TabsContent value="materialMismatch" className="flex-1 flex flex-col mt-0">
                {renderTableSection(
                  "materialMismatch",
                  "Material Properties Mismatches",
                  "Material properties (Alumina, Iron, AP) that don't match between TL sheet and LIFT-ACCOUNTS sheet for the same raw material.",
                  filteredMaterialMismatchData,
                  MATERIAL_MISMATCH_COLUMNS_META,
                  visibleMaterialMismatchColumns
                )}
              </TabsContent>


            </Tabs>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}