"use client";

import { useState, useEffect, useMemo, useCallback } from "react";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Filter,
  CheckCircle2,
  History,
  Loader2,
  AlertTriangle,
  Info,
  Users,
  X,
  Search,
  Upload,
  TrendingDown,
} from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useNotification } from "../context/NotificationContext";
import { supabase } from "../supabase";
import { uploadFileToStorage } from "../utils/storageUtils";
import { fetchMasterData } from "../utils/masterDataUtils";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

// Helper function to format datetime
const formatDateTime = (isoString) => {
  if (!isoString) return "-";
  const date = new Date(isoString);
  const day = date.getDate().toString().padStart(2, "0");
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const year = date.getFullYear();
  const hours = date.getHours().toString().padStart(2, "0");
  const minutes = date.getMinutes().toString().padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
};

export default function ThreeParty() {
  const [pendingData, setPendingData] = useState([]);
  const [historyData, setHistoryData] = useState([]);
  const [filteredPendingData, setFilteredPendingData] = useState([]);
  const [filteredHistoryData, setFilteredHistoryData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [refreshData, setRefreshData] = useState(false);
  const [selectedIndent, setSelectedIndent] = useState(null);
  const [selectedHistory, setSelectedHistory] = useState(null);
  const [openDialog, setOpenDialog] = useState(false);

  // Filter states
  const [selectedDate, setSelectedDate] = useState("");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedHistoryDate, setSelectedHistoryDate] = useState("");
  const [historySearchQuery, setHistorySearchQuery] = useState("");

  const { user } = useAuth();
  const { updateCount } = useNotification();
  const [vendorMasterOptions, setVendorMasterOptions] = useState([]);

  const fetchVendorMasterOptions = useCallback(async () => {
    try {
      const masterData = await fetchMasterData();
      setVendorMasterOptions(masterData.vendorOptions || []);
    } catch (error) {
      console.error("Error fetching vendor options:", error);
    }
  }, []);

  useEffect(() => {
    fetchVendorMasterOptions();
  }, [fetchVendorMasterOptions]);

  // Fetch data from Supabase
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      setError(null);
      try {
        const { data, error: fetchError } = await supabase
          .from("INDENT-PO")
          .select("*");

        if (fetchError) throw fetchError;

        // Filter by firm name
        let filteredData = data;
        if (user?.firmName && user.firmName.toLowerCase() !== "all") {
          filteredData = data.filter(
            (row) =>
              row["Firm Name"] &&
              String(row["Firm Name"]).toLowerCase() ===
                user.firmName.toLowerCase(),
          );
        }

        // Process pending data (Planned6 is not null and Actual6 is null)
        const pending = filteredData
          .filter(
            (row) =>
              row["Planned6"] !== null &&
              row["Planned6"] !== "" &&
              (!row["Actual6"] || row["Actual6"] === ""),
          )
          .map((row) => ({
            id: row.id,
            indentId: row["Indent Id."] || "",
            firmName: row["Firm Name"] || "",
            indenter: row["Generated By"] || "",
            department: row["Type Of Indent"] || "",
            product: row["Material"] || "",
            comparisonSheet: row["Comparison Sheet"] || "",
            planned6: row["Planned6"] || "",
            actual6: row["Actual6"] || "",
            vendors: [
              {
                name: row["Vendor Name 1"] || "",
                rateType:
                  row["Select Rate Type 1"] === "Basic Rate"
                    ? "basic"
                    : "withTax",
                rate: parseFloat(row["Rate 1"]) || 0,
                withTax: row["With Tax or Not 1"] === "No" ? "no" : "yes",
                gstPercent: parseInt(row["Tax Value 1"]) || 0,
                paymentTerm: row["Payment Term 1"] || "",
                whatsapp: row["Whatsapp Number 1"] || "",
                email: row["Email Id 1"] || "",
              },
              {
                name: row["Vendor Name 2"] || "",
                rateType:
                  row["Select Rate Type 2"] === "Basic Rate"
                    ? "basic"
                    : "withTax",
                rate: parseFloat(row["Rate 2"]) || 0,
                withTax: row["With Tax or Not 2"] === "No" ? "no" : "yes",
                gstPercent: parseInt(row["Tax Value 2"]) || 0,
                paymentTerm: row["Payment Term 2"] || "",
                whatsapp: row["Whatsapp Number 2"] || "",
                email: row["Email Id 2"] || "",
              },
              {
                name: row["Vendor Name 3"] || "",
                rateType:
                  row["Select Rate Type 3"] === "Basic Rate"
                    ? "basic"
                    : "withTax",
                rate: parseFloat(row["Rate 3"]) || 0,
                withTax: row["With Tax or Not 3"] === "No" ? "no" : "yes",
                gstPercent: parseInt(row["Tax Value 3"]) || 0,
                paymentTerm: row["Payment Term 3"] || "",
                whatsapp: row["Whatsapp Number 3"] || "",
                email: row["Email Id 3"] || "",
              },
            ],
          }));

        // Process history data (Planned6 is not null and Actual6 is not null)
        const history = filteredData
          .filter(
            (row) =>
              row["Planned6"] !== null &&
              row["Planned6"] !== "" &&
              row["Actual6"] !== null &&
              row["Actual6"] !== "",
          )
          .map((row) => ({
            id: row.id,
            indentId: row["Indent Id."] || "",
            firmName: row["Firm Name"] || "",
            indenter: row["Generated By"] || "",
            department: row["Type Of Indent"] || "",
            product: row["Material"] || "",
            actual6: row["Actual6"] || "",
            vendor: [
              row["Approved Vendor Name"] || "",
              row["Approved Rate"]?.toString() || "0",
              row["Approved Payment Term"] || "",
              row["With Tax or Not 4"] || "Yes",
              row["Tax Value 4"]?.toString() || "0",
            ],
            approvedDate: row["Approved Date"] || "",
          }))
          .sort((a, b) => {
            const dateA = new Date(a.actual6);
            const dateB = new Date(b.actual6);
            return dateB.getTime() - dateA.getTime();
          });

        setPendingData(pending);
        setFilteredPendingData(pending);
        setHistoryData(history);
        setFilteredHistoryData(history);

        // Update notification count
        updateCount("vendor", pending.length);
      } catch (err) {
        console.error("Error fetching data:", err);
        setError("Failed to load data: " + err.message);
        toast.error("Failed to load data", { description: err.message });
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [refreshData, user, updateCount]);

  // Filter pending data
  useEffect(() => {
    let filtered = [...pendingData];

    if (selectedDate) {
      filtered = filtered.filter((item) => {
        const itemDate = new Date(item.planned6).toISOString().split("T")[0];
        return itemDate === selectedDate;
      });
    }

    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(
        (item) =>
          item.indentId.toLowerCase().includes(query) ||
          item.firmName.toLowerCase().includes(query) ||
          item.indenter.toLowerCase().includes(query) ||
          item.department.toLowerCase().includes(query) ||
          item.product.toLowerCase().includes(query),
      );
    }

    setFilteredPendingData(filtered);
  }, [selectedDate, searchQuery, pendingData]);

  // Filter history data
  useEffect(() => {
    let filtered = [...historyData];

    if (selectedHistoryDate) {
      filtered = filtered.filter((item) => {
        const itemDate = new Date(item.actual6).toISOString().split("T")[0];
        return itemDate === selectedHistoryDate;
      });
    }

    if (historySearchQuery.trim()) {
      const query = historySearchQuery.toLowerCase();
      filtered = filtered.filter(
        (item) =>
          item.indentId.toLowerCase().includes(query) ||
          item.firmName.toLowerCase().includes(query) ||
          item.indenter.toLowerCase().includes(query) ||
          item.department.toLowerCase().includes(query) ||
          item.product.toLowerCase().includes(query),
      );
    }

    setFilteredHistoryData(filtered);
  }, [selectedHistoryDate, historySearchQuery, historyData]);

  const clearAllFilters = () => {
    setSelectedDate("");
    setSearchQuery("");
  };

  const clearAllHistoryFilters = () => {
    setSelectedHistoryDate("");
    setHistorySearchQuery("");
  };

  // Form state for Three Party
  const [vendorForms, setVendorForms] = useState([
    {
      name: "",
      rateType: "basic",
      rate: 0,
      withTax: "no",
      gstPercent: 0,
      paymentTerm: "",
      whatsapp: "",
      email: "",
    },
    {
      name: "",
      rateType: "basic",
      rate: 0,
      withTax: "no",
      gstPercent: 0,
      paymentTerm: "",
      whatsapp: "",
      email: "",
    },
    {
      name: "",
      rateType: "basic",
      rate: 0,
      withTax: "no",
      gstPercent: 0,
      paymentTerm: "",
      whatsapp: "",
      email: "",
    },
  ]);
  const [comparisonSheetFile, setComparisonSheetFile] = useState(null);
  const [currentStep, setCurrentStep] = useState(1);
  const [historyRate, setHistoryRate] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const updateVendorForm = (index, field, value) => {
    setVendorForms((prev) => {
      const newForms = [...prev];
      newForms[index] = { ...newForms[index], [field]: value };
      return newForms;
    });
  };

  // Calculate lowest rate among vendors
  const lowestRate = useMemo(() => {
    const validRates = vendorForms
      .filter((v) => v.name && v.rate > 0)
      .map((v) => v.rate);
    return validRates.length > 0 ? Math.min(...validRates) : null;
  }, [vendorForms]);

  async function onSubmit() {
    if (!selectedIndent) return;

    // Validate at least one vendor selected
    const hasVendor = vendorForms.some((v) => v.name);
    if (!hasVendor) {
      toast.error("Please select at least one vendor");
      return;
    }

    setIsSubmitting(true);
    try {
      let comparisonSheetUrl = selectedIndent.comparisonSheet || "";
      if (comparisonSheetFile) {
        const res = await uploadFileToStorage(
          comparisonSheetFile,
          "image",
          "comparison_sheets",
        );
        comparisonSheetUrl = res.url;
      }

      const formatVendor = (v) => {
        const rateTypeText = v.rateType === "basic" ? "Basic Rate" : "With Tax";
        let withTaxOrNot = "";
        let taxValue = 0;

        if (v.rateType === "basic") {
          if (v.withTax === "yes") {
            withTaxOrNot = "Yes";
            taxValue = 0;
          } else if (v.withTax === "no") {
            withTaxOrNot = "No";
            taxValue = v.gstPercent || 0;
          }
        } else {
          withTaxOrNot = "Yes";
          taxValue = 0;
        }

        return {
          name: v.name || "",
          rateType: rateTypeText,
          rate: v.rate?.toString() || "0",
          withTaxOrNot,
          taxValue: taxValue.toString(),
          paymentTerm: v.paymentTerm || "",
          whatsapp: v.whatsapp || "",
          email: v.email || "",
        };
      };

      const v1 = formatVendor(vendorForms[0]);
      const v2 = formatVendor(vendorForms[1]);
      const v3 = formatVendor(vendorForms[2]);

      const { error: updateError } = await supabase
        .from("INDENT-PO")
        .update({
          Actual6: new Date().toISOString(),
          "Vendor Name 1": v1.name,
          "Select Rate Type 1": v1.rateType,
          "Rate 1": v1.rate,
          "With Tax or Not 1": v1.withTaxOrNot,
          "Tax Value 1": v1.taxValue,
          "Payment Term 1": v1.paymentTerm,
          "Whatsapp Number 1": v1.whatsapp,
          "Email Id 1": v1.email,

          "Vendor Name 2": v2.name,
          "Select Rate Type 2": v2.rateType,
          "Rate 2": v2.rate,
          "With Tax or Not 2": v2.withTaxOrNot,
          "Tax Value 2": v2.taxValue,
          "Payment Term 2": v2.paymentTerm,
          "Whatsapp Number 2": v2.whatsapp,
          "Email Id 2": v2.email,

          "Vendor Name 3": v3.name,
          "Select Rate Type 3": v3.rateType,
          "Rate 3": v3.rate,
          "With Tax or Not 3": v3.withTaxOrNot,
          "Tax Value 3": v3.taxValue,
          "Payment Term 3": v3.paymentTerm,
          "Whatsapp Number 3": v3.whatsapp,
          "Email Id 3": v3.email,

          "Comparison Sheet": comparisonSheetUrl,
          Planned7: new Date().toISOString(),
        })
        .eq("id", selectedIndent.id);

      if (updateError) throw updateError;

      toast.success(`Approved ${selectedIndent.indentId}`);
      setOpenDialog(false);
      setVendorForms([
        {
          name: "",
          rateType: "basic",
          rate: 0,
          withTax: "no",
          gstPercent: 0,
          paymentTerm: "",
          whatsapp: "",
          email: "",
        },
        {
          name: "",
          rateType: "basic",
          rate: 0,
          withTax: "no",
          gstPercent: 0,
          paymentTerm: "",
          whatsapp: "",
          email: "",
        },
        {
          name: "",
          rateType: "basic",
          rate: 0,
          withTax: "no",
          gstPercent: 0,
          paymentTerm: "",
          whatsapp: "",
          email: "",
        },
      ]);
      setComparisonSheetFile(null);
      setCurrentStep(1);
      setTimeout(() => setRefreshData((prev) => !prev), 1000);
    } catch (error) {
      console.error("Error updating vendors:", error);
      toast.error("Failed to update vendors");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function onSubmitHistoryUpdate() {
    if (!selectedHistory) return;
    if (historyRate <= 0) {
      toast.error("Rate must be greater than 0");
      return;
    }

    setIsSubmitting(true);
    try {
      const { error: updateError } = await supabase
        .from("INDENT-PO")
        .update({
          "Approved Rate": historyRate.toString(),
          "Approved Date": new Date().toISOString(),
        })
        .eq("id", selectedHistory.id);

      if (updateError) throw updateError;

      toast.success(`Updated rate for ${selectedHistory.indentId}`);
      setOpenDialog(false);
      setHistoryRate(0);
      setRefreshData((prev) => !prev);
    } catch (error) {
      console.error("Error updating rate:", error);
      toast.error("Failed to update rate");
    } finally {
      setIsSubmitting(false);
    }
  }

  useEffect(() => {
    if (selectedHistory) {
      setHistoryRate(parseFloat(selectedHistory.vendor[1]) || 0);
    }
  }, [selectedHistory]);

  return (
    <Card className="relative w-full max-w-full mx-auto bg-white border-0 shadow-lg">
      <CardHeader className="p-6 border-b border-gray-100 bg-gradient-to-r from-gray-50 to-white">
        <CardTitle className="flex items-center gap-3 text-xl font-semibold text-gray-800">
          <div className="p-2 bg-green-100 rounded-lg">
            <Users className="h-5 w-5 text-[#7da23a]" />
          </div>
          Three Party Rate Approval
        </CardTitle>
        <CardDescription className="mt-1 text-sm text-gray-500">
          Compare vendor rates and make approval decisions
        </CardDescription>
        {user?.firmName && user.firmName.toLowerCase() !== "all" && (
          <Badge
            variant="outline"
            className="mt-2 text-green-700 border-green-200 bg-green-50"
          >
            {user.firmName}
          </Badge>
        )}
      </CardHeader>

      <CardContent className="p-6">
        <Tabs defaultValue="pending" className="w-full">
          <TabsList className="grid w-full max-w-[300px] grid-cols-2 mb-6 bg-gray-100 p-1 rounded-lg">
            <TabsTrigger
              value="pending"
              className="flex items-center gap-2 rounded-md data-[state=active]:bg-white data-[state=active]:shadow-sm"
            >
              <CheckCircle2 className="w-4 h-4" />
              Pending
              <Badge
                variant="secondary"
                className="ml-1 px-1.5 py-0.5 text-xs bg-gray-200"
              >
                {pendingData.length}
              </Badge>
            </TabsTrigger>
            <TabsTrigger
              value="history"
              className="flex items-center gap-2 rounded-md data-[state=active]:bg-white data-[state=active]:shadow-sm"
            >
              <History className="w-4 h-4" />
              History
            </TabsTrigger>
          </TabsList>

          {/* Pending Tab */}
          <TabsContent value="pending" className="mt-0">
            {/* Filters Section - Reduced visual noise */}
            <div className="p-4 mb-6 bg-gray-50/50 rounded-xl">
              <div className="flex items-center gap-2 mb-3">
                <Filter className="w-4 h-4 text-gray-400" />
                <span className="text-sm font-medium text-gray-600">
                  Filters
                </span>
                {(selectedDate || searchQuery) && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={clearAllFilters}
                    className="ml-auto text-xs text-gray-500 h-7 hover:text-gray-700"
                  >
                    Clear all
                  </Button>
                )}
              </div>
              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <Label className="block mb-1 text-xs text-gray-500">
                    Planned Date
                  </Label>
                  <Input
                    type="date"
                    value={selectedDate}
                    onChange={(e) => setSelectedDate(e.target.value)}
                    className="text-sm border-gray-200 h-9 focus:ring-1 focus:ring-green-500"
                  />
                </div>
                <div>
                  <Label className="block mb-1 text-xs text-gray-500">
                    Search
                  </Label>
                  <div className="relative">
                    <Search className="absolute w-4 h-4 text-gray-400 transform -translate-y-1/2 left-3 top-1/2" />
                    <Input
                      placeholder="Indent, Product, Department..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="text-sm border-gray-200 pl-9 h-9 focus:ring-1 focus:ring-green-500"
                    />
                  </div>
                </div>
              </div>
            </div>

            {loading ? (
              <div className="flex items-center justify-center h-64">
                <Loader2 className="w-8 h-8 text-green-500 animate-spin" />
              </div>
            ) : error ? (
              <div className="p-8 text-center bg-red-50 rounded-xl">
                <AlertTriangle className="w-12 h-12 mx-auto mb-3 text-red-500" />
                <p className="text-red-600">{error}</p>
                <Button
                  onClick={() => setRefreshData((p) => !p)}
                  className="mt-4 bg-red-600 hover:bg-red-700"
                >
                  Retry
                </Button>
              </div>
            ) : filteredPendingData.length === 0 ? (
              <div className="py-12 text-center">
                <Info className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                <p className="text-gray-500">No pending approvals</p>
              </div>
            ) : (
              <div className="overflow-x-auto border border-gray-100 rounded-xl">
                <Table>
                  <TableHeader className="bg-gray-50">
                    <TableRow className="border-b border-gray-200">
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Action
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Indent & Product
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Firm & Department
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Planned Date
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Vendor Rates
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredPendingData.map((indent) => (
                      <TableRow
                        key={indent.id}
                        className="transition-colors border-b border-gray-100 hover:bg-gray-50/50"
                      >
                        <TableCell className="px-4 py-3">
                          <Button
                            onClick={() => {
                              setSelectedIndent(indent);
                              setSelectedHistory(null);
                              setOpenDialog(true);
                              setVendorForms(indent.vendors);
                              setComparisonSheetFile(null);
                              setCurrentStep(1);
                            }}
                            className="h-8 px-3 text-xs bg-[#7da23a] hover:bg-[#6b8e2f] text-white shadow-none"
                          >
                            Approve
                          </Button>
                        </TableCell>
                        <TableCell className="px-4 py-3">
                          <div className="text-sm font-medium text-gray-800">
                            {indent.indentId}
                          </div>
                          <div className="text-xs text-gray-400 mt-0.5">
                            {indent.product}
                          </div>
                        </TableCell>
                        <TableCell className="px-4 py-3">
                          <div className="text-sm text-gray-700">
                            {indent.firmName}
                          </div>
                          <div className="text-xs text-gray-400">
                            {indent.department}
                          </div>
                        </TableCell>
                        <TableCell className="px-4 py-3 text-sm text-gray-600">
                          {formatDateTime(indent.planned6)}
                        </TableCell>
                        <TableCell className="px-4 py-3">
                          <div className="flex flex-wrap gap-1.5">
                            {indent.vendors
                              .filter((v) => v.name)
                              .map((vendor, index) => (
                                <Badge
                                  key={index}
                                  variant="outline"
                                  className="text-xs px-2 py-0.5 bg-white border-gray-200"
                                >
                                  {vendor.name.split(" ").slice(0, 2).join(" ")}{" "}
                                  ₹{vendor.rate}
                                </Badge>
                              ))}
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </TabsContent>

          {/* History Tab */}
          <TabsContent value="history" className="mt-0">
            <div className="p-4 mb-6 bg-gray-50/50 rounded-xl">
              <div className="flex items-center gap-2 mb-3">
                <Filter className="w-4 h-4 text-gray-400" />
                <span className="text-sm font-medium text-gray-600">
                  Filters
                </span>
                {(selectedHistoryDate || historySearchQuery) && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={clearAllHistoryFilters}
                    className="ml-auto text-xs h-7"
                  >
                    Clear all
                  </Button>
                )}
              </div>
              <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                <div>
                  <Label className="block mb-1 text-xs text-gray-500">
                    Approval Date
                  </Label>
                  <Input
                    type="date"
                    value={selectedHistoryDate}
                    onChange={(e) => setSelectedHistoryDate(e.target.value)}
                    className="text-sm border-gray-200 h-9"
                  />
                </div>
                <div>
                  <Label className="block mb-1 text-xs text-gray-500">
                    Search
                  </Label>
                  <div className="relative">
                    <Search className="absolute w-4 h-4 text-gray-400 transform -translate-y-1/2 left-3 top-1/2" />
                    <Input
                      placeholder="Indent, Product, Department..."
                      value={historySearchQuery}
                      onChange={(e) => setHistorySearchQuery(e.target.value)}
                      className="text-sm border-gray-200 pl-9 h-9"
                    />
                  </div>
                </div>
              </div>
            </div>

            {loading ? (
              <div className="flex items-center justify-center h-64">
                <Loader2 className="w-8 h-8 text-green-500 animate-spin" />
              </div>
            ) : filteredHistoryData.length === 0 ? (
              <div className="py-12 text-center">
                <Info className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                <p className="text-gray-500">No history found</p>
              </div>
            ) : (
              <div className="overflow-x-auto border border-gray-100 rounded-xl">
                <Table>
                  <TableHeader className="bg-gray-50">
                    <TableRow className="border-b border-gray-200">
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Action
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Approval Date
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Indent & Product
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Approved Vendor
                      </TableHead>
                      <TableHead className="px-4 py-3 text-xs font-semibold text-gray-600 uppercase">
                        Rate
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredHistoryData.map((indent) => (
                      <TableRow
                        key={indent.id}
                        className="border-b border-gray-100 hover:bg-gray-50/50"
                      >
                        <TableCell className="px-4 py-3">
                          <Button
                            variant="outline"
                            onClick={() => {
                              setSelectedHistory(indent);
                              setSelectedIndent(null);
                              setOpenDialog(true);
                            }}
                            className="h-8 px-3 text-xs"
                          >
                            Update
                          </Button>
                        </TableCell>
                        <TableCell className="px-4 py-3 text-sm text-gray-600">
                          {formatDateTime(indent.actual6)}
                        </TableCell>
                        <TableCell className="px-4 py-3">
                          <div className="text-sm font-medium text-gray-800">
                            {indent.indentId}
                          </div>
                          <div className="text-xs text-gray-400">
                            {indent.product}
                          </div>
                        </TableCell>
                        <TableCell className="px-4 py-3">
                          <Badge className="text-green-700 bg-green-100 border-0">
                            {indent.vendor[0]}
                          </Badge>
                        </TableCell>
                        <TableCell className="px-4 py-3 text-sm font-medium">
                          ₹{indent.vendor[1]}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </TabsContent>
        </Tabs>
      </CardContent>

      {/* Redesigned Dialog with Side-by-Side Vendor Comparison */}
      <Dialog open={openDialog} onOpenChange={setOpenDialog}>
        <DialogContent className="sm:max-w-[900px] p-0 overflow-hidden rounded-2xl">
          {selectedIndent && (
            <div className="flex flex-col h-full max-h-[85vh]">
              {/* Header with Indent Info */}
              <DialogHeader className="px-6 pt-6 pb-3 border-b border-gray-100">
                <DialogTitle className="text-lg font-semibold text-gray-800">
                  Approve Vendors
                </DialogTitle>
                <div className="grid grid-cols-3 gap-3 p-3 mt-2 text-sm rounded-lg bg-gray-50">
                  <div>
                    <span className="block text-xs text-gray-500">
                      Indent ID
                    </span>
                    <span className="font-medium text-gray-800">
                      {selectedIndent.indentId}
                    </span>
                  </div>
                  <div>
                    <span className="block text-xs text-gray-500">
                      Department
                    </span>
                    <span className="text-gray-700">
                      {selectedIndent.department}
                    </span>
                  </div>
                  <div>
                    <span className="block text-xs text-gray-500">Product</span>
                    <span className="font-medium text-gray-700">
                      {selectedIndent.product}
                    </span>
                  </div>
                </div>
              </DialogHeader>

              {/* Step Indicator */}
              <div className="px-6 pt-4">
                <div className="flex items-center gap-2 mb-3 text-xs text-gray-500">
                  <span
                    className={`flex items-center justify-center w-6 h-6 rounded-full ${currentStep >= 1 ? "bg-green-100 text-green-600" : "bg-gray-100"} text-xs font-medium`}
                  >
                    1
                  </span>
                  <span
                    className={`h-px w-8 ${currentStep >= 2 ? "bg-green-300" : "bg-gray-200"}`}
                  ></span>
                  <span
                    className={`flex items-center justify-center w-6 h-6 rounded-full ${currentStep >= 2 ? "bg-green-100 text-green-600" : "bg-gray-100"} text-xs font-medium`}
                  >
                    2
                  </span>
                  <span
                    className={`h-px w-8 ${currentStep >= 3 ? "bg-green-300" : "bg-gray-200"}`}
                  ></span>
                  <span
                    className={`flex items-center justify-center w-6 h-6 rounded-full ${currentStep >= 3 ? "bg-green-100 text-green-600" : "bg-gray-100"} text-xs font-medium`}
                  >
                    3
                  </span>
                </div>
                <div className="flex justify-between mb-4 text-xs text-gray-500">
                  <span>Vendor Details</span>
                  <span>Compare Rates</span>
                  <span>Upload & Submit</span>
                </div>
              </div>

              <div className="flex-1 px-6 pb-4 overflow-y-auto">
                {/* Step 1: Vendor Details - Side by Side Comparison */}
                <div className="space-y-4">
                  <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                    {[0, 1, 2].map((idx) => {
                      const isLowest =
                        vendorForms[idx].name &&
                        vendorForms[idx].rate > 0 &&
                        vendorForms[idx].rate === lowestRate;
                      return (
                        <div
                          key={idx}
                          className={`p-4 rounded-xl transition-all ${isLowest ? "border-2 border-green-400 bg-green-50/30" : "border border-gray-200 bg-white"}`}
                        >
                          <div className="flex items-center justify-between mb-3">
                            <span className="text-sm font-semibold text-gray-700">
                              Vendor {idx + 1}
                            </span>
                            {isLowest && (
                              <Badge className="text-xs text-white bg-green-500">
                                <TrendingDown className="w-3 h-3 mr-1" />
                                Lowest
                              </Badge>
                            )}
                          </div>

                          <div className="space-y-3">
                            <div>
                              <Label className="block mb-1 text-xs text-gray-500">
                                Vendor Name
                              </Label>
                              <Select
                                value={vendorForms[idx].name}
                                onValueChange={(value) =>
                                  updateVendorForm(idx, "name", value)
                                }
                              >
                                <SelectTrigger className="text-sm border-gray-200 h-9">
                                  <SelectValue placeholder="Select vendor" />
                                </SelectTrigger>
                                <SelectContent>
                                  {vendorMasterOptions.map(
                                    (vendor, vendorIndex) => (
                                      <SelectItem
                                        key={`vendor-${idx}-${vendorIndex}`}
                                        value={vendor}
                                      >
                                        {vendor}
                                      </SelectItem>
                                    ),
                                  )}
                                </SelectContent>
                              </Select>
                            </div>

                            <div className="grid grid-cols-2 gap-2">
                              <div>
                                <Label className="block mb-1 text-xs text-gray-500">
                                  Rate Type
                                </Label>
                                <Select
                                  value={vendorForms[idx].rateType}
                                  onValueChange={(v) =>
                                    updateVendorForm(idx, "rateType", v)
                                  }
                                >
                                  <SelectTrigger className="text-sm border-gray-200 h-9">
                                    <SelectValue />
                                  </SelectTrigger>
                                  <SelectContent>
                                    <SelectItem value="basic">
                                      Basic Rate
                                    </SelectItem>
                                    <SelectItem value="withTax">
                                      With Tax
                                    </SelectItem>
                                  </SelectContent>
                                </Select>
                              </div>

                              <div>
                                <Label className="block mb-1 text-xs text-gray-500">
                                  Rate (₹)
                                </Label>
                                <Input
                                  type="number"
                                  value={vendorForms[idx].rate || ""}
                                  onChange={(e) =>
                                    updateVendorForm(
                                      idx,
                                      "rate",
                                      parseFloat(e.target.value) || 0,
                                    )
                                  }
                                  className="text-sm border-gray-200 h-9"
                                  placeholder="0.00"
                                />
                              </div>
                            </div>

                            {vendorForms[idx].rateType === "basic" &&
                              vendorForms[idx].withTax === "no" && (
                                <div>
                                  <Label className="block mb-1 text-xs text-gray-500">
                                    GST %
                                  </Label>
                                  <Select
                                    value={
                                      vendorForms[idx].gstPercent?.toString() ||
                                      "0"
                                    }
                                    onValueChange={(v) =>
                                      updateVendorForm(
                                        idx,
                                        "gstPercent",
                                        parseInt(v),
                                      )
                                    }
                                  >
                                    <SelectTrigger className="text-sm border-gray-200 h-9">
                                      <SelectValue placeholder="Select GST" />
                                    </SelectTrigger>
                                    <SelectContent>
                                      <SelectItem value="5">5%</SelectItem>
                                      <SelectItem value="18">18%</SelectItem>
                                      <SelectItem value="40">40%</SelectItem>
                                    </SelectContent>
                                  </Select>
                                </div>
                              )}

                            <div>
                              <Label className="block mb-1 text-xs text-gray-500">
                                Payment Term
                              </Label>
                              <Select
                                value={vendorForms[idx].paymentTerm}
                                onValueChange={(v) =>
                                  updateVendorForm(idx, "paymentTerm", v)
                                }
                              >
                                <SelectTrigger className="text-sm border-gray-200 h-9">
                                  <SelectValue placeholder="Select term" />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="Advance">
                                    Advance
                                  </SelectItem>
                                  <SelectItem value="After Delivery">
                                    After Delivery
                                  </SelectItem>
                                  <SelectItem value="Credit 30 Days">
                                    Credit 30 Days
                                  </SelectItem>
                                  <SelectItem value="Credit 60 Days">
                                    Credit 60 Days
                                  </SelectItem>
                                </SelectContent>
                              </Select>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Step 2: Comparison Sheet Upload */}
                  <div className="pt-4 mt-6 border-t border-gray-100">
                    <div className="mb-3 text-sm font-semibold text-gray-700">
                      Step 3: Upload Comparison Sheet
                    </div>
                    <div className="p-6 text-center transition-colors border-2 border-gray-200 border-dashed cursor-pointer rounded-xl hover:bg-gray-50">
                      <Upload className="w-8 h-8 mx-auto mb-2 text-gray-400" />
                      <p className="text-sm font-medium text-gray-700">
                        {comparisonSheetFile
                          ? comparisonSheetFile.name
                          : "Upload Comparison Sheet"}
                      </p>
                      <p className="mt-1 text-xs text-gray-400">
                        PDF, JPG, PNG (max 10MB)
                      </p>
                      <input
                        type="file"
                        accept=".pdf,.jpg,.jpeg,.png"
                        className="hidden"
                        id="comparison-sheet-upload"
                        onChange={(e) =>
                          setComparisonSheetFile(e.target.files?.[0] || null)
                        }
                      />
                      <Button
                        variant="outline"
                        size="sm"
                        className="mt-3 text-xs"
                        onClick={() =>
                          document
                            .getElementById("comparison-sheet-upload")
                            ?.click()
                        }
                      >
                        Choose File
                      </Button>
                    </div>
                  </div>
                </div>
              </div>

              {/* Sticky Footer */}
              <div className="sticky bottom-0 bg-white border-t border-gray-200 p-4 px-6 flex justify-end gap-3 rounded-b-2xl shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.05)]">
                <Button
                  variant="outline"
                  onClick={() => setOpenDialog(false)}
                  className="px-6"
                >
                  Cancel
                </Button>
                <Button
                  onClick={onSubmit}
                  disabled={isSubmitting || !vendorForms.some((v) => v.name)}
                  className="px-6 bg-[#7da23a] hover:bg-[#6b8e2f] text-white"
                >
                  {isSubmitting ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : null}
                  Submit Approval
                </Button>
              </div>
            </div>
          )}

          {selectedHistory && (
            <DialogHeader className="p-6 pb-2">
              <DialogTitle className="text-lg font-semibold">
                Update Approved Rate
              </DialogTitle>
              <div className="p-3 mt-3 rounded-lg bg-gray-50">
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <div>
                    <span className="block text-xs text-gray-500">
                      Indent ID
                    </span>
                    <span className="font-medium">
                      {selectedHistory.indentId}
                    </span>
                  </div>
                  <div>
                    <span className="block text-xs text-gray-500">Vendor</span>
                    <span className="font-medium">
                      {selectedHistory.vendor[0]}
                    </span>
                  </div>
                </div>
              </div>
              <div className="mt-4 space-y-3">
                <Label className="text-sm font-medium">Current Rate</Label>
                <div className="text-2xl font-bold text-gray-800">
                  ₹{selectedHistory.vendor[1]}
                </div>
                <Label className="mt-4 text-sm font-medium">New Rate</Label>
                <Input
                  type="number"
                  step="0.01"
                  value={historyRate}
                  onChange={(e) =>
                    setHistoryRate(parseFloat(e.target.value) || 0)
                  }
                  placeholder="Enter new rate"
                  className="text-lg"
                />
              </div>
              <div className="flex gap-3 mt-6">
                <Button
                  variant="outline"
                  onClick={() => setOpenDialog(false)}
                  className="flex-1"
                >
                  Cancel
                </Button>
                <Button
                  className="flex-1 bg-[#7da23a] hover:bg-[#6b8e2f]"
                  disabled={historyRate <= 0 || isSubmitting}
                  onClick={onSubmitHistoryUpdate}
                >
                  {isSubmitting ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    "Update Rate"
                  )}
                </Button>
              </div>
            </DialogHeader>
          )}
        </DialogContent>
      </Dialog>
    </Card>
  );
}
