import { supabase } from "../supabase";

/**
 * Fetches all Master data from Supabase and returns organized dropdown options.
 * This replaces the previous Google Sheets Master data fetching.
 * 
 * @returns {Promise<Object>} Object containing arrays of dropdown options
 */
export async function fetchMasterData() {
    try {
        let data = [];
        let from = 0;
        let hasMore = true;

        while (hasMore) {
            const { data: chunk, error } = await supabase
                .from("Master")
                .select("*")
                .range(from, from + 999);

            if (error) throw error;

            if (chunk && chunk.length > 0) {
                data = [...data, ...chunk];
                if (chunk.length < 1000) {
                    hasMore = false;
                } else {
                    from += 1000;
                }
            } else {
                hasMore = false;
            }
        }

        if (!data || data.length === 0) {
            console.warn("Master table is empty");
            return {
                generatedByOptions: [],
                vendorOptions: [],
                materialOptions: [],
                indentTypeOptions: [],
                rateTypeOptions: [],
                areaLiftingOptions: [],
                typeOptions: [],
                transporterOptions: [],
                transporterMasterOptions: [],
                transporterMasterMap: {},
                firmNameOptions: [],
                kycFormTypeOptions: [],
                vendorKycOptions: [],
                productNameOptions: [],
                transporter2Options: [],
                gstNumbers: [],
                bankAccountNumbers: [],
                ifscCodes: [],
                phoneNumbers: [],
                emails: []
            };
        }

        // Extract unique values for each dropdown type
        const extractUniqueValues = (columnName) => {
            const values = new Set();
            data.forEach(row => {
                const value = row[columnName];
                if (value && String(value).trim() !== "") {
                    values.add(String(value).trim());
                }
            });
            return Array.from(values).sort();
        };

        const transporterMasterRecords = data
            .filter((row) => String(row["Type Of KYC Form"] || "").trim().toLowerCase() === "transportation")
            .map((row) => ({
                name: String(row["Transporter Name 2"] || row["Transporter Name"] || "").trim(),
                rateType: String(row["Transport Rate Type"] || "").trim(),
                rate: String(row["Transport Rate"] || "").trim(),
            }))
            .filter((row) => row.name);

        const transporterMasterMap = transporterMasterRecords.reduce((acc, row) => {
            acc[row.name] = row;
            return acc;
        }, {});

        const transporterNames = Array.from(new Set([
            ...extractUniqueValues("Transporter Name"),
            ...extractUniqueValues("Transporter Name 2"),
            ...transporterMasterRecords.map((item) => item.name),
        ])).sort();

        const transporterMasterOptions = transporterNames.map((name) => ({
            name,
            rateType: transporterMasterMap[name]?.rateType || "",
            rate: transporterMasterMap[name]?.rate || "",
        }));

        // Create mapping for Firm Name to Generated By
        const firmNameMapping = {};
        data.forEach(row => {
            const firm = row["Firm Name"];
            const genBy = row["Generated By"];
            if (firm && genBy && String(firm).trim() !== "" && String(genBy).trim() !== "") {
                firmNameMapping[String(firm).trim()] = String(genBy).trim();
            }
        });

        return {
            // Mapping for auto-population
            firmNameMapping,

            // For IndentForm
            generatedByOptions: extractUniqueValues("Generated By"),
            vendorOptions: extractUniqueValues("Vendor Name"),
            materialOptions: extractUniqueValues("Raw Material Name"),
            indentTypeOptions: extractUniqueValues("Type Of Indent"),

            // For lift-material
            rateTypeOptions: extractUniqueValues("Type Of Rate"),
            areaLiftingOptions: extractUniqueValues("Area Lifting"),
            typeOptions: extractUniqueValues("Type"),
            transporterOptions: transporterNames,
            transporterMasterOptions,
            transporterMasterMap,

            // For KYC Page
            firmNameOptions: extractUniqueValues("Firm Name"),
            kycFormTypeOptions: extractUniqueValues("Type Of KYC Form"),
            vendorKycOptions: extractUniqueValues("Vendor Name KYC"),
            productNameOptions: extractUniqueValues("Product Name"),
            transporter2Options: extractUniqueValues("Transporter Name 2"),

            // Additional fields that might be used
            gstNumbers: extractUniqueValues("GST Number"),
            bankAccountNumbers: extractUniqueValues("Current Bank A.C. No"),
            ifscCodes: extractUniqueValues("IFSC Code"),
            phoneNumbers: extractUniqueValues("Phone Number"),
            emails: extractUniqueValues("Email"),
            uomOptions: extractUniqueValues("UOM")
        };

    } catch (error) {
        console.error("Error fetching Master data from Supabase:", error);
        throw new Error(`Failed to fetch Master data: ${error.message}`);
    }
}

/**
 * Fetches Master data and returns formatted options for Select components
 * @returns {Promise<Object>} Object containing arrays of {value, label} objects
 */
export async function fetchMasterDataForSelects() {
    try {
        const data = await fetchMasterData();

        const formatOptions = (values) => {
            return values.map(value => ({
                value: value,
                label: value
            }));
        };

        return {
            generatedByOptions: formatOptions(data.generatedByOptions),
            vendorOptions: formatOptions(data.vendorOptions),
            materialOptions: formatOptions(data.materialOptions),
            indentTypeOptions: formatOptions(data.indentTypeOptions),
            rateTypeOptions: formatOptions(data.rateTypeOptions),
            areaLiftingOptions: formatOptions(data.areaLiftingOptions),
            typeOptions: formatOptions(data.typeOptions),
            transporterOptions: formatOptions(data.transporterOptions),
            transporterMasterOptions: data.transporterMasterOptions.map((item) => ({
                value: item.name,
                label: item.name,
                rateType: item.rateType,
                rate: item.rate,
            })),
            transporterMasterMap: data.transporterMasterMap,
            firmNameOptions: formatOptions(data.firmNameOptions),
            kycFormTypeOptions: formatOptions(data.kycFormTypeOptions),
            vendorKycOptions: formatOptions(data.vendorKycOptions),
            productNameOptions: formatOptions(data.productNameOptions),
            transporter2Options: formatOptions(data.transporter2Options),
            gstNumbers: formatOptions(data.gstNumbers),
            bankAccountNumbers: formatOptions(data.bankAccountNumbers),
            ifscCodes: formatOptions(data.ifscCodes),
            phoneNumbers: formatOptions(data.phoneNumbers),
            emails: formatOptions(data.emails)
        };
    } catch (error) {
        console.error("Error formatting Master data:", error);
        throw error;
    }
}
