import { supabase } from "../supabase";

/**
 * Fetches all Master data from Supabase and returns organized dropdown options.
 * This replaces the previous Google Sheets Master data fetching.
 * 
 * @returns {Promise<Object>} Object containing arrays of dropdown options
 */
export async function fetchMasterData() {
    try {
        const { data, error } = await supabase
            .from("Master")
            .select("*");

        if (error) throw error;

        if (!data || data.length === 0) {
            console.warn("Master table is empty");
            return {
                generatedByOptions: [],
                vendorOptions: [],
                materialOptions: [],
                indentTypeOptions: [],
                rateTypeOptions: [],
                areaLiftingOptions: [],
                typeOptions: [],
                transporterOptions: [],
                firmNameOptions: [],
                kycFormTypeOptions: [],
                vendorKycOptions: [],
                productNameOptions: [],
                transporter2Options: [],
                gstNumbers: [],
                bankAccountNumbers: [],
                ifscCodes: [],
                phoneNumbers: [],
                emails: []
            };
        }

        // Extract unique values for each dropdown type
        const extractUniqueValues = (columnName) => {
            const values = new Set();
            data.forEach(row => {
                const value = row[columnName];
                if (value && String(value).trim() !== "") {
                    values.add(String(value).trim());
                }
            });
            return Array.from(values).sort();
        };

        return {
            // For IndentForm
            generatedByOptions: extractUniqueValues("Generated By"),
            vendorOptions: extractUniqueValues("Vendor Name"),
            materialOptions: extractUniqueValues("Raw Material Name"),
            indentTypeOptions: extractUniqueValues("Type Of Indent"),

            // For lift-material
            rateTypeOptions: extractUniqueValues("Type Of Rate"),
            areaLiftingOptions: extractUniqueValues("Area Lifting"),
            typeOptions: extractUniqueValues("Type"),
            transporterOptions: extractUniqueValues("Transporter Name"),

            // For KYC Page
            firmNameOptions: extractUniqueValues("Firm Name"),
            kycFormTypeOptions: extractUniqueValues("Type Of KYC Form"),
            vendorKycOptions: extractUniqueValues("Vendor Name KYC"),
            productNameOptions: extractUniqueValues("Product Name"),
            transporter2Options: extractUniqueValues("Transporter Name 2"),

            // Additional fields that might be used
            gstNumbers: extractUniqueValues("GST Number"),
            bankAccountNumbers: extractUniqueValues("Current Bank A.C. No"),
            ifscCodes: extractUniqueValues("IFSC Code"),
            phoneNumbers: extractUniqueValues("Phone Number"),
            emails: extractUniqueValues("Email")
        };

    } catch (error) {
        console.error("Error fetching Master data from Supabase:", error);
        throw new Error(`Failed to fetch Master data: ${error.message}`);
    }
}

/**
 * Fetches Master data and returns formatted options for Select components
 * @returns {Promise<Object>} Object containing arrays of {value, label} objects
 */
export async function fetchMasterDataForSelects() {
    try {
        const data = await fetchMasterData();

        const formatOptions = (values) => {
            return values.map(value => ({
                value: value,
                label: value
            }));
        };

        return {
            generatedByOptions: formatOptions(data.generatedByOptions),
            vendorOptions: formatOptions(data.vendorOptions),
            materialOptions: formatOptions(data.materialOptions),
            indentTypeOptions: formatOptions(data.indentTypeOptions),
            rateTypeOptions: formatOptions(data.rateTypeOptions),
            areaLiftingOptions: formatOptions(data.areaLiftingOptions),
            typeOptions: formatOptions(data.typeOptions),
            transporterOptions: formatOptions(data.transporterOptions),
            firmNameOptions: formatOptions(data.firmNameOptions),
            kycFormTypeOptions: formatOptions(data.kycFormTypeOptions),
            vendorKycOptions: formatOptions(data.vendorKycOptions),
            productNameOptions: formatOptions(data.productNameOptions),
            transporter2Options: formatOptions(data.transporter2Options),
            gstNumbers: formatOptions(data.gstNumbers),
            bankAccountNumbers: formatOptions(data.bankAccountNumbers),
            ifscCodes: formatOptions(data.ifscCodes),
            phoneNumbers: formatOptions(data.phoneNumbers),
            emails: formatOptions(data.emails)
        };
    } catch (error) {
        console.error("Error formatting Master data:", error);
        throw error;
    }
}
